ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  next@>=15.5.0-canary.0 <15.5.7: '>=15.5.7'
  tar@=7.5.1: '>=7.5.2'
  validator@<13.15.20: '>=13.15.20'
  validator@<13.15.22: '>=13.15.22'
