/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Arive API
 * Arive API with OpenAPI documentation
 * OpenAPI spec version: 0.0.2
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  CampaignSchema,
  CampaignUpdateSchema,
  CampaignsIdGetCampaign400,
  CampaignsIdUpdateCampaign400
} from '../ariveAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary GetCampaign
 */
export const campaignsIdGetCampaign = (
    id: unknown,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CampaignSchema>(
      {url: `/campaigns/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getCampaignsIdGetCampaignQueryKey = (id?: unknown,) => {
    return [
    `/campaigns/${id}`
    ] as const;
    }

    
export const getCampaignsIdGetCampaignQueryOptions = <TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(id: unknown, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignsIdGetCampaignQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignsIdGetCampaign>>> = ({ signal }) => campaignsIdGetCampaign(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignsIdGetCampaignQueryResult = NonNullable<Awaited<ReturnType<typeof campaignsIdGetCampaign>>>
export type CampaignsIdGetCampaignQueryError = CampaignsIdGetCampaign400


export function useCampaignsIdGetCampaign<TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(
 id: unknown, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignsIdGetCampaign>>,
          TError,
          Awaited<ReturnType<typeof campaignsIdGetCampaign>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignsIdGetCampaign<TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(
 id: unknown, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof campaignsIdGetCampaign>>,
          TError,
          Awaited<ReturnType<typeof campaignsIdGetCampaign>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignsIdGetCampaign<TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(
 id: unknown, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetCampaign
 */

export function useCampaignsIdGetCampaign<TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(
 id: unknown, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignsIdGetCampaignQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getCampaignsIdGetCampaignSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(id: unknown, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCampaignsIdGetCampaignQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof campaignsIdGetCampaign>>> = ({ signal }) => campaignsIdGetCampaign(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CampaignsIdGetCampaignSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof campaignsIdGetCampaign>>>
export type CampaignsIdGetCampaignSuspenseQueryError = CampaignsIdGetCampaign400


export function useCampaignsIdGetCampaignSuspense<TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(
 id: unknown, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignsIdGetCampaignSuspense<TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(
 id: unknown, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCampaignsIdGetCampaignSuspense<TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(
 id: unknown, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetCampaign
 */

export function useCampaignsIdGetCampaignSuspense<TData = Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError = CampaignsIdGetCampaign400>(
 id: unknown, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof campaignsIdGetCampaign>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCampaignsIdGetCampaignSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary UpdateCampaign
 */
export const campaignsIdUpdateCampaign = (
    id: unknown,
    campaignUpdateSchema: CampaignUpdateSchema,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CampaignSchema>(
      {url: `/campaigns/${id}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: campaignUpdateSchema, signal
    },
      );
    }
  


export const getCampaignsIdUpdateCampaignMutationOptions = <TError = CampaignsIdUpdateCampaign400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsIdUpdateCampaign>>, TError,{id: unknown;data: CampaignUpdateSchema}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof campaignsIdUpdateCampaign>>, TError,{id: unknown;data: CampaignUpdateSchema}, TContext> => {

const mutationKey = ['campaignsIdUpdateCampaign'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof campaignsIdUpdateCampaign>>, {id: unknown;data: CampaignUpdateSchema}> = (props) => {
          const {id,data} = props ?? {};

          return  campaignsIdUpdateCampaign(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CampaignsIdUpdateCampaignMutationResult = NonNullable<Awaited<ReturnType<typeof campaignsIdUpdateCampaign>>>
    export type CampaignsIdUpdateCampaignMutationBody = CampaignUpdateSchema
    export type CampaignsIdUpdateCampaignMutationError = CampaignsIdUpdateCampaign400

    /**
 * @summary UpdateCampaign
 */
export const useCampaignsIdUpdateCampaign = <TError = CampaignsIdUpdateCampaign400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof campaignsIdUpdateCampaign>>, TError,{id: unknown;data: CampaignUpdateSchema}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof campaignsIdUpdateCampaign>>,
        TError,
        {id: unknown;data: CampaignUpdateSchema},
        TContext
      > => {

      const mutationOptions = getCampaignsIdUpdateCampaignMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    