repos:
  - repo: local
    hooks:
      - id: linting
        name: prettier (local)
        language: system
        # run from frontend so plugins resolve from frontend/node_modules
        entry: bash -lc 'cd frontend && pnpm run -s lint --'
        # pre-commit will append the file list AFTER the `--`
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|scss|html|md)$
        exclude: ^frontend/(node_modules|dist|build|.next|out)/

  - repo: local
    hooks:
      - id: prettier
        name: prettier (local)
        language: system
        # run from frontend so plugins resolve from frontend/node_modules
        entry: bash -lc 'cd frontend && pnpm run -s format:write --'
        # pre-commit will append the file list AFTER the `--`
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|scss|html|md)$
        exclude: ^frontend/(node_modules|dist|build|.next|out)/

  # Ruff for backend linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        files: ^backend/.*\.py$
        args: [--fix]
      - id: ruff-format
        files: ^backend/.*\.py$

  # Terraform formatting and validation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
        files: ^infra/.*\.tf$
      - id: terraform_validate
        files: ^infra/.*\.tf$
