/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateUserSchema,
  CreateUserUserResponseBody,
  GetUserUserResponseBody,
  ListUsersUserResponseBody,
  UserWaitlistFormSchema,
  UsersCreateUser400,
  UsersSignupAddUserToWaitlist400,
  UsersUserIdGetUser400
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary ListUsers
 */
export const usersListUsers = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<ListUsersUserResponseBody[]>(
      {url: `/users`, method: 'GET', signal
    },
      );
    }
  

export const getUsersListUsersQueryKey = () => {
    return [`/users`] as const;
    }

    
export const getUsersListUsersQueryOptions = <TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersListUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersListUsers>>> = ({ signal }) => usersListUsers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof usersListUsers>>>
export type UsersListUsersQueryError = unknown


export function useUsersListUsers<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersListUsers>>,
          TError,
          Awaited<ReturnType<typeof usersListUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersListUsers<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersListUsers>>,
          TError,
          Awaited<ReturnType<typeof usersListUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersListUsers<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ListUsers
 */

export function useUsersListUsers<TData = Awaited<ReturnType<typeof usersListUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersListUsers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersListUsersQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary CreateUser
 */
export const usersCreateUser = (
    createUserSchema: CreateUserSchema,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CreateUserUserResponseBody>(
      {url: `/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserSchema, signal
    },
      );
    }
  


export const getUsersCreateUserMutationOptions = <TError = UsersCreateUser400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersCreateUser>>, TError,{data: CreateUserSchema}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersCreateUser>>, TError,{data: CreateUserSchema}, TContext> => {

const mutationKey = ['usersCreateUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersCreateUser>>, {data: CreateUserSchema}> = (props) => {
          const {data} = props ?? {};

          return  usersCreateUser(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersCreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof usersCreateUser>>>
    export type UsersCreateUserMutationBody = CreateUserSchema
    export type UsersCreateUserMutationError = UsersCreateUser400

    /**
 * @summary CreateUser
 */
export const useUsersCreateUser = <TError = UsersCreateUser400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersCreateUser>>, TError,{data: CreateUserSchema}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersCreateUser>>,
        TError,
        {data: CreateUserSchema},
        TContext
      > => {

      const mutationOptions = getUsersCreateUserMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary GetUser
 */
export const usersUserIdGetUser = (
    userId: number,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserUserResponseBody>(
      {url: `/users/${userId}`, method: 'GET', signal
    },
      );
    }
  

export const getUsersUserIdGetUserQueryKey = (userId?: number,) => {
    return [`/users/${userId}`] as const;
    }

    
export const getUsersUserIdGetUserQueryOptions = <TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersUserIdGetUserQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersUserIdGetUser>>> = ({ signal }) => usersUserIdGetUser(userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersUserIdGetUserQueryResult = NonNullable<Awaited<ReturnType<typeof usersUserIdGetUser>>>
export type UsersUserIdGetUserQueryError = UsersUserIdGetUser400


export function useUsersUserIdGetUser<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUserIdGetUser>>,
          TError,
          Awaited<ReturnType<typeof usersUserIdGetUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUserIdGetUser<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersUserIdGetUser>>,
          TError,
          Awaited<ReturnType<typeof usersUserIdGetUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersUserIdGetUser<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetUser
 */

export function useUsersUserIdGetUser<TData = Awaited<ReturnType<typeof usersUserIdGetUser>>, TError = UsersUserIdGetUser400>(
 userId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersUserIdGetUser>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersUserIdGetUserQueryOptions(userId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary AddUserToWaitlist
 */
export const usersSignupAddUserToWaitlist = (
    userWaitlistFormSchema: UserWaitlistFormSchema,
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/users/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userWaitlistFormSchema, signal
    },
      );
    }
  


export const getUsersSignupAddUserToWaitlistMutationOptions = <TError = UsersSignupAddUserToWaitlist400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersSignupAddUserToWaitlist>>, TError,{data: UserWaitlistFormSchema}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersSignupAddUserToWaitlist>>, TError,{data: UserWaitlistFormSchema}, TContext> => {

const mutationKey = ['usersSignupAddUserToWaitlist'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersSignupAddUserToWaitlist>>, {data: UserWaitlistFormSchema}> = (props) => {
          const {data} = props ?? {};

          return  usersSignupAddUserToWaitlist(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersSignupAddUserToWaitlistMutationResult = NonNullable<Awaited<ReturnType<typeof usersSignupAddUserToWaitlist>>>
    export type UsersSignupAddUserToWaitlistMutationBody = UserWaitlistFormSchema
    export type UsersSignupAddUserToWaitlistMutationError = UsersSignupAddUserToWaitlist400

    /**
 * @summary AddUserToWaitlist
 */
export const useUsersSignupAddUserToWaitlist = <TError = UsersSignupAddUserToWaitlist400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersSignupAddUserToWaitlist>>, TError,{data: UserWaitlistFormSchema}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersSignupAddUserToWaitlist>>,
        TError,
        {data: UserWaitlistFormSchema},
        TContext
      > => {

      const mutationOptions = getUsersSignupAddUserToWaitlistMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    