/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * ManagerLab
 * Private schema of ManagerLab with Scalar OpenAPI docs
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeliverableResponseSchema,
  DeliverableUpdateSchema,
  DeliverablesIdGetDeliverable400,
  DeliverablesIdUpdateDeliverable400
} from '../managerLab.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary GetDeliverable
 */
export const deliverablesIdGetDeliverable = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DeliverableResponseSchema>(
      {url: `/deliverables/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getDeliverablesIdGetDeliverableQueryKey = (id?: string,) => {
    return [
    `/deliverables/${id}`
    ] as const;
    }

    
export const getDeliverablesIdGetDeliverableQueryOptions = <TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeliverablesIdGetDeliverableQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>> = ({ signal }) => deliverablesIdGetDeliverable(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeliverablesIdGetDeliverableQueryResult = NonNullable<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>>
export type DeliverablesIdGetDeliverableQueryError = DeliverablesIdGetDeliverable400


export function useDeliverablesIdGetDeliverable<TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>,
          TError,
          Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeliverablesIdGetDeliverable<TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>,
          TError,
          Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeliverablesIdGetDeliverable<TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetDeliverable
 */

export function useDeliverablesIdGetDeliverable<TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeliverablesIdGetDeliverableQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getDeliverablesIdGetDeliverableSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeliverablesIdGetDeliverableQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>> = ({ signal }) => deliverablesIdGetDeliverable(id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeliverablesIdGetDeliverableSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>>
export type DeliverablesIdGetDeliverableSuspenseQueryError = DeliverablesIdGetDeliverable400


export function useDeliverablesIdGetDeliverableSuspense<TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeliverablesIdGetDeliverableSuspense<TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeliverablesIdGetDeliverableSuspense<TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetDeliverable
 */

export function useDeliverablesIdGetDeliverableSuspense<TData = Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError = DeliverablesIdGetDeliverable400>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof deliverablesIdGetDeliverable>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeliverablesIdGetDeliverableSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary UpdateDeliverable
 */
export const deliverablesIdUpdateDeliverable = (
    id: string,
    deliverableUpdateSchema: DeliverableUpdateSchema,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DeliverableResponseSchema>(
      {url: `/deliverables/${id}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deliverableUpdateSchema, signal
    },
      );
    }
  


export const getDeliverablesIdUpdateDeliverableMutationOptions = <TError = DeliverablesIdUpdateDeliverable400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deliverablesIdUpdateDeliverable>>, TError,{id: string;data: DeliverableUpdateSchema}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deliverablesIdUpdateDeliverable>>, TError,{id: string;data: DeliverableUpdateSchema}, TContext> => {

const mutationKey = ['deliverablesIdUpdateDeliverable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deliverablesIdUpdateDeliverable>>, {id: string;data: DeliverableUpdateSchema}> = (props) => {
          const {id,data} = props ?? {};

          return  deliverablesIdUpdateDeliverable(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeliverablesIdUpdateDeliverableMutationResult = NonNullable<Awaited<ReturnType<typeof deliverablesIdUpdateDeliverable>>>
    export type DeliverablesIdUpdateDeliverableMutationBody = DeliverableUpdateSchema
    export type DeliverablesIdUpdateDeliverableMutationError = DeliverablesIdUpdateDeliverable400

    /**
 * @summary UpdateDeliverable
 */
export const useDeliverablesIdUpdateDeliverable = <TError = DeliverablesIdUpdateDeliverable400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deliverablesIdUpdateDeliverable>>, TError,{id: string;data: DeliverableUpdateSchema}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deliverablesIdUpdateDeliverable>>,
        TError,
        {id: string;data: DeliverableUpdateSchema},
        TContext
      > => {

      const mutationOptions = getDeliverablesIdUpdateDeliverableMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    