"""remove_legacy_media_fields

Revision ID: 06ea3c9fc6cd
Revises: 92a8ce5f8d2a
Create Date: 2025-10-02 00:48:39.551042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06ea3c9fc6cd"
down_revision: Union[str, Sequence[str], None] = "92a8ce5f8d2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saq_versions")
    op.drop_index(op.f("saq_jobs_status_queue_group_key_idx"), table_name="saq_jobs")
    op.drop_index(
        op.f("saq_jobs_status_queue_priority_scheduled_idx"), table_name="saq_jobs"
    )
    op.drop_table("saq_jobs")
    op.drop_index(op.f("saq_stats_expire_at_idx"), table_name="saq_stats")
    op.drop_index(op.f("saq_stats_queue_key_idx"), table_name="saq_stats")
    op.drop_table("saq_stats")
    op.drop_column("media", "filename")
    op.drop_column("media", "thumnbnail_link")
    op.drop_column("media", "image_link")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media", sa.Column("image_link", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "media",
        sa.Column("thumnbnail_link", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "media", sa.Column("filename", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.create_table(
        "saq_stats",
        sa.Column("worker_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("expire_at", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("queue_key", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("worker_id", name=op.f("saq_stats_pkey")),
    )
    op.create_index(
        op.f("saq_stats_queue_key_idx"), "saq_stats", ["queue_key"], unique=False
    )
    op.create_index(
        op.f("saq_stats_expire_at_idx"), "saq_stats", ["expire_at"], unique=False
    )
    op.create_table(
        "saq_jobs",
        sa.Column("key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("lock_key", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("job", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column("queue", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("status", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "priority",
            sa.SMALLINT(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("group_key", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "scheduled",
            sa.BIGINT(),
            server_default=sa.text("EXTRACT(epoch FROM now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("expire_at", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("saq_jobs_pkey")),
    )
    op.create_index(
        op.f("saq_jobs_status_queue_priority_scheduled_idx"),
        "saq_jobs",
        ["status", "queue", "priority", "scheduled"],
        unique=False,
    )
    op.create_index(
        op.f("saq_jobs_status_queue_group_key_idx"),
        "saq_jobs",
        ["status", "queue", "group_key"],
        unique=False,
    )
    op.create_table(
        "saq_versions",
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
