"""remove_legacy_media_fields

Revision ID: 06ea3c9fc6cd
Revises: 92a8ce5f8d2a
Create Date: 2025-10-02 00:48:39.551042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "06ea3c9fc6cd"
down_revision: Union[str, Sequence[str], None] = "92a8ce5f8d2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media", "filename")
    op.drop_column("media", "thumnbnail_link")
    op.drop_column("media", "image_link")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media", sa.Column("image_link", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "media",
        sa.Column("thumnbnail_link", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "media", sa.Column("filename", sa.TEXT(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
