"""add roster birthdate

Revision ID: 0d2e21bdebce
Revises: 77e2b91a11d3
Create Date: 2025-10-21 09:28:12.699437

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d2e21bdebce"
down_revision: str | Sequence[str] | None = "77e2b91a11d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns",
        sa.Column(
            "compensation_structure",
            sa.Enum(
                "FLAT_FEE",
                "PER_DELIVERABLE",
                "PERFORMANCE_BASED",
                name="compensationstructure",
            ),
            nullable=True,
        ),
    )
    op.drop_column("deliverables", "compensation_structure")
    op.add_column("roster", sa.Column("birthdate", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roster", "birthdate")
    op.add_column(
        "deliverables",
        sa.Column(
            "compensation_structure",
            postgresql.ENUM(
                "FLAT_FEE",
                "PER_DELIVERABLE",
                "PERFORMANCE_BASED",
                name="compensationstructure",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("campaigns", "compensation_structure")
    # ### end Alembic commands ###
