"""add documents table

Revision ID: 1321d4e2f093
Revises: 1b6e7f2a0a0b
Create Date: 2025-11-03 14:11:40.010323

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.state_machine.models import TextEnum
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "1321d4e2f093"
down_revision: str | Sequence[str] | None = "1b6e7f2a0a0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("file_key", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_type", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("thumbnail_key", sa.Text(), nullable=True),
        sa.Column("team_id", SqidType(), nullable=False),
        sa.Column("campaign_id", SqidType(), nullable=True),
        sa.Column("state", TextEnum(), server_default="PENDING", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_key"),
    )
    op.create_index(op.f("ix_documents_campaign_id"), "documents", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_documents_deleted_at"), "documents", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_documents_state"), "documents", ["state"], unique=False)
    op.create_index(op.f("ix_documents_team_id"), "documents", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_team_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_state"), table_name="documents")
    op.drop_index(op.f("ix_documents_deleted_at"), table_name="documents")
    op.drop_index(op.f("ix_documents_campaign_id"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
