"""Harden inbound email processing

Revision ID: 13a5281c9181
Revises: ede48058260c
Create Date: 2025-11-24 17:40:08.381288

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.state_machine.models import TextEnum
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "13a5281c9181"
down_revision: Union[str, Sequence[str], None] = "ede48058260c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("inbound_emails", "from_email", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("inbound_emails", "team_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(op.f("inbound_emails_team_id_fkey"), "inbound_emails", type_="foreignkey")
    op.create_foreign_key(None, "inbound_emails", "teams", ["team_id"], ["id"], ondelete="CASCADE")
    op.create_index(
        "ix_user_single_owner", "roles", ["user_id"], unique=True, postgresql_where=sa.text("role_level = 'OWNER'")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_single_owner", table_name="roles", postgresql_where=sa.text("role_level = 'OWNER'"))
    op.drop_constraint(None, "inbound_emails", type_="foreignkey")
    op.create_foreign_key(
        op.f("inbound_emails_team_id_fkey"), "inbound_emails", "teams", ["team_id"], ["id"], ondelete="RESTRICT"
    )
    op.alter_column("inbound_emails", "team_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("inbound_emails", "from_email", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
