"""add_inbound_email_table

Revision ID: 230e504ec19d
Revises: 38185b743a7f
Create Date: 2025-11-13 15:38:14.470764

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "230e504ec19d"
down_revision: Union[str, Sequence[str], None] = "38185b743a7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_emails",
        sa.Column("s3_bucket", sa.Text(), nullable=False),
        sa.Column("s3_key", sa.Text(), nullable=False),
        sa.Column("from_email", sa.Text(), nullable=True),
        sa.Column("to_email", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("ses_message_id", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("attachments_json", sa.JSON(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("team_id", app.utils.sqids.SqidType(), nullable=True),
        sa.Column("state", app.state_machine.models.TextEnum(), server_default="RECEIVED", nullable=False),
        sa.Column("id", app.utils.sqids.SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ses_message_id"),
    )
    op.create_index(op.f("ix_inbound_emails_deleted_at"), "inbound_emails", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_inbound_emails_from_email"), "inbound_emails", ["from_email"], unique=False)
    op.create_index(op.f("ix_inbound_emails_s3_key"), "inbound_emails", ["s3_key"], unique=True)
    op.create_index(op.f("ix_inbound_emails_state"), "inbound_emails", ["state"], unique=False)
    op.create_index(op.f("ix_inbound_emails_team_id"), "inbound_emails", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inbound_emails_team_id"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_state"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_s3_key"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_from_email"), table_name="inbound_emails")
    op.drop_index(op.f("ix_inbound_emails_deleted_at"), table_name="inbound_emails")
    op.drop_table("inbound_emails")
    # ### end Alembic commands ###
