"""to demo

Revision ID: 3fad5453e29b
Revises: 82cd4683f530
Create Date: 2025-09-28 20:22:50.453297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3fad5453e29b"
down_revision: Union[str, Sequence[str], None] = "82cd4683f530"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "campaigns",
        sa.Column("state", sa.Text(), server_default="DRAFT", nullable=False),
    )
    op.create_index(op.f("ix_campaigns_state"), "campaigns", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campaigns_state"), table_name="campaigns")
    op.drop_column("campaigns", "state")
    # ### end Alembic commands ###
