"""refactor thread read status to append-only log

Revision ID: 521dafcba94d
Revises: daf5c7a1f059
Create Date: 2025-10-22 16:36:25.845429

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "521dafcba94d"
down_revision: str | Sequence[str] | None = "daf5c7a1f059"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "thread_read_statuses",
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_constraint(op.f("uq_user_thread_read_status"), "thread_read_statuses", type_="unique")
    op.create_index(
        "ix_thread_read_status_lookup",
        "thread_read_statuses",
        ["thread_id", "user_id", "read_at"],
        unique=False,
    )
    op.drop_column("thread_read_statuses", "last_read_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "thread_read_statuses",
        sa.Column(
            "last_read_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("ix_thread_read_status_lookup", table_name="thread_read_statuses")
    op.create_unique_constraint(
        op.f("uq_user_thread_read_status"),
        "thread_read_statuses",
        ["thread_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("thread_read_statuses", "read_at")
    # ### end Alembic commands ###
