"""add rls to dashboard

Revision ID: 56ef7b94a04f
Revises: 39b4f471b02b
Create Date: 2025-10-20 15:58:51.758009

"""

from collections.abc import Sequence

from alembic_utils.pg_policy import PGPolicy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56ef7b94a04f"
down_revision: str | Sequence[str] | None = "39b4f471b02b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_dashboards_team_scope_policy = PGPolicy(
        schema="public",
        signature="team_scope_policy",
        on_entity="public.dashboards",
        definition="AS PERMISSIVE\n                            FOR ALL\n                            USING (\n                                team_id = current_setting('app.team_id', true)::int\n                                OR current_setting('app.team_id', true) IS NULL\n                            )",
    )
    op.create_entity(public_dashboards_team_scope_policy)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_dashboards_team_scope_policy = PGPolicy(
        schema="public",
        signature="team_scope_policy",
        on_entity="public.dashboards",
        definition="AS PERMISSIVE\n                            FOR ALL\n                            USING (\n                                team_id = current_setting('app.team_id', true)::int\n                                OR current_setting('app.team_id', true) IS NULL\n                            )",
    )
    op.drop_entity(public_dashboards_team_scope_policy)

    # ### end Alembic commands ###
