"""Update address fields to Text and add AddressType enum

Revision ID: 6416d060aa23
Revises: 96e6568cba43
Create Date: 2025-12-30 09:09:11.085463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text
from alembic_utils.pg_policy import PGPolicy
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '6416d060aa23'
down_revision: Union[str, Sequence[str], None] = '96e6568cba43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the AddressType enum first
    addresstype_enum = sa.Enum('HOME', 'WORK', 'OTHER', name='addresstype')
    addresstype_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('addresses', 'zip',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('addresses', 'country',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.Text(),
               existing_nullable=False)
    # Convert address_type column to use the enum
    # Use USING clause to cast existing values
    op.execute("ALTER TABLE addresses ALTER COLUMN address_type TYPE addresstype USING address_type::addresstype")
    op.enable_rls('public', 'addresses')
    public_addresses_team_scope_policy = PGPolicy(
        schema="public",
        signature="team_scope_policy",
        on_entity="public.addresses",
        definition="AS PERMISSIVE\n                        FOR ALL\n                        USING (\n                            NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n                            OR (NULLIF(current_setting('app.team_id', true), '') IS NOT NULL\n                                AND team_id = NULLIF(current_setting('app.team_id', true), '')::int)\n                        )"
    )
    op.create_entity(public_addresses_team_scope_policy)

    public_alembic_version_arive_insert = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='arive', grant='INSERT', with_grant_option=False)
    op.drop_entity(public_alembic_version_arive_insert)

    public_alembic_version_arive_select = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='arive', grant='SELECT', with_grant_option=False)
    op.drop_entity(public_alembic_version_arive_select)

    public_alembic_version_arive_update = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='arive', grant='UPDATE', with_grant_option=False)
    op.drop_entity(public_alembic_version_arive_update)

    public_alembic_version_arive_delete = PGGrantTable(schema='public', table='alembic_version', columns=[], role='arive', grant='DELETE', with_grant_option=False)
    op.drop_entity(public_alembic_version_arive_delete)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_alembic_version_arive_delete = PGGrantTable(schema='public', table='alembic_version', columns=[], role='arive', grant='DELETE', with_grant_option=False)
    op.create_entity(public_alembic_version_arive_delete)

    public_alembic_version_arive_update = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='arive', grant='UPDATE', with_grant_option=False)
    op.create_entity(public_alembic_version_arive_update)

    public_alembic_version_arive_select = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='arive', grant='SELECT', with_grant_option=False)
    op.create_entity(public_alembic_version_arive_select)

    public_alembic_version_arive_insert = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='arive', grant='INSERT', with_grant_option=False)
    op.create_entity(public_alembic_version_arive_insert)

    public_addresses_team_scope_policy = PGPolicy(
        schema="public",
        signature="team_scope_policy",
        on_entity="public.addresses",
        definition="AS PERMISSIVE\n                        FOR ALL\n                        USING (\n                            NULLIF(current_setting('app.is_system_mode', true), '')::boolean IS TRUE\n                            OR (NULLIF(current_setting('app.team_id', true), '') IS NOT NULL\n                                AND team_id = NULLIF(current_setting('app.team_id', true), '')::int)\n                        )"
    )
    op.drop_entity(public_addresses_team_scope_policy)

    op.disable_rls('public', 'addresses')
    # Convert address_type back to varchar
    op.execute("ALTER TABLE addresses ALTER COLUMN address_type TYPE VARCHAR(50)")
    op.alter_column('addresses', 'country',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    op.alter_column('addresses', 'zip',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('addresses', 'state',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # Drop the enum type
    addresstype_enum = sa.Enum('HOME', 'WORK', 'OTHER', name='addresstype')
    addresstype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
