"""

Revision ID: 738c65a4ebae
Revises: 125656db763e
Create Date: 2025-11-07 17:08:30.890486

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "738c65a4ebae"
down_revision: str | Sequence[str] | None = "125656db763e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_messages",
        sa.Column("to_email", sa.Text(), nullable=False),
        sa.Column("from_email", sa.Text(), nullable=False),
        sa.Column("reply_to_email", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("ses_message_id", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("template_name", sa.Text(), nullable=True),
        sa.Column("team_id", SqidType(), nullable=False),
        sa.Column(
            "state",
            sa.Text(),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ses_message_id"),
    )
    op.create_index(
        op.f("ix_email_messages_deleted_at"),
        "email_messages",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(op.f("ix_email_messages_state"), "email_messages", ["state"], unique=False)
    op.create_index(op.f("ix_email_messages_team_id"), "email_messages", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_messages_team_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_state"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_deleted_at"), table_name="email_messages")
    op.drop_table("email_messages")
    # ### end Alembic commands ###
