"""Add file upload fields to media model

Revision ID: 92a8ce5f8d2a
Revises: d88e3812dfc0
Create Date: 2025-10-01 23:20:58.815761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92a8ce5f8d2a"
down_revision: Union[str, Sequence[str], None] = "d88e3812dfc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with default values to handle existing data
    op.add_column("media", sa.Column("file_key", sa.Text(), nullable=True))
    op.add_column("media", sa.Column("file_name", sa.Text(), nullable=True))
    op.add_column("media", sa.Column("file_type", sa.Text(), nullable=True))
    op.add_column("media", sa.Column("file_size", sa.BigInteger(), nullable=True))
    op.add_column("media", sa.Column("mime_type", sa.Text(), nullable=True))
    op.add_column("media", sa.Column("thumbnail_key", sa.Text(), nullable=True))
    op.add_column("media", sa.Column("status", sa.Text(), nullable=True))

    # Set defaults for existing rows
    op.execute(
        "UPDATE media SET file_key = 'legacy/' || id::text WHERE file_key IS NULL"
    )
    op.execute(
        "UPDATE media SET file_name = filename WHERE file_name IS NULL AND filename IS NOT NULL"
    )
    op.execute("UPDATE media SET file_type = 'image' WHERE file_type IS NULL")
    op.execute("UPDATE media SET file_size = 0 WHERE file_size IS NULL")
    op.execute("UPDATE media SET mime_type = 'image/jpeg' WHERE mime_type IS NULL")
    op.execute("UPDATE media SET status = 'ready' WHERE status IS NULL")

    # Make columns non-nullable after setting defaults
    op.alter_column("media", "file_key", nullable=False)
    op.alter_column("media", "file_name", nullable=False)
    op.alter_column("media", "file_type", nullable=False)
    op.alter_column("media", "file_size", nullable=False)
    op.alter_column("media", "mime_type", nullable=False)
    op.alter_column("media", "status", nullable=False)

    op.create_unique_constraint("uq_media_file_key", "media", ["file_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_media_file_key", "media", type_="unique")
    op.drop_column("media", "status")
    op.drop_column("media", "thumbnail_key")
    op.drop_column("media", "mime_type")
    op.drop_column("media", "file_size")
    op.drop_column("media", "file_type")
    op.drop_column("media", "file_name")
    op.drop_column("media", "file_key")
    # ### end Alembic commands ###
