"""

Revision ID: 96e6568cba43
Revises: c6496061f143
Create Date: 2025-12-29 16:40:51.833721

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic_utils.pg_grant_table import PGGrantTable

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "96e6568cba43"
down_revision: str | Sequence[str] | None = "c6496061f143"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("address1", sa.Text(), nullable=False),
        sa.Column("address2", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("zip", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("address_type", sa.String(length=50), nullable=True),
        sa.Column("team_id", SqidType(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_addresses_deleted_at"), "addresses", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_addresses_team_id"), "addresses", ["team_id"], unique=False)
    op.add_column("roster", sa.Column("gender", sa.Text(), nullable=True))
    op.add_column("roster", sa.Column("address_id", SqidType(), nullable=True))
    op.create_index(op.f("ix_roster_address_id"), "roster", ["address_id"], unique=False)
    op.create_foreign_key(None, "roster", "addresses", ["address_id"], ["id"], ondelete="SET NULL")
    public_alembic_version_arive_insert = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="INSERT",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_arive_insert)

    public_alembic_version_arive_select = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="SELECT",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_arive_select)

    public_alembic_version_arive_update = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="UPDATE",
        with_grant_option=False,
    )
    op.drop_entity(public_alembic_version_arive_update)

    public_alembic_version_arive_delete = PGGrantTable(
        schema="public", table="alembic_version", columns=[], role="arive", grant="DELETE", with_grant_option=False
    )
    op.drop_entity(public_alembic_version_arive_delete)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_alembic_version_arive_delete = PGGrantTable(
        schema="public", table="alembic_version", columns=[], role="arive", grant="DELETE", with_grant_option=False
    )
    op.create_entity(public_alembic_version_arive_delete)

    public_alembic_version_arive_update = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="UPDATE",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_arive_update)

    public_alembic_version_arive_select = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="SELECT",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_arive_select)

    public_alembic_version_arive_insert = PGGrantTable(
        schema="public",
        table="alembic_version",
        columns=["version_num"],
        role="arive",
        grant="INSERT",
        with_grant_option=False,
    )
    op.create_entity(public_alembic_version_arive_insert)

    op.drop_constraint(None, "roster", type_="foreignkey")
    op.drop_index(op.f("ix_roster_address_id"), table_name="roster")
    op.drop_column("roster", "address_id")
    op.drop_column("roster", "gender")
    op.drop_index(op.f("ix_addresses_team_id"), table_name="addresses")
    op.drop_index(op.f("ix_addresses_deleted_at"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
