"""Add widgets table

Revision ID: a618447426b6
Revises: e9279ec998bb
Create Date: 2025-11-24 22:24:17.057899

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "a618447426b6"
down_revision: str | Sequence[str] | None = "e9279ec998bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create widgets table
    op.create_table(
        "widgets",
        sa.Column("dashboard_id", SqidType(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "query", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("position_x", sa.Integer(), nullable=False),
        sa.Column("position_y", sa.Integer(), nullable=False),
        sa.Column("size_w", sa.Integer(), nullable=False),
        sa.Column("size_h", sa.Integer(), nullable=False),
        sa.Column("team_id", SqidType(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dashboard_id"], ["dashboards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_widgets_dashboard_id"), "widgets", ["dashboard_id"], unique=False)
    op.create_index(op.f("ix_widgets_deleted_at"), "widgets", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_widgets_team_id"), "widgets", ["team_id"], unique=False)

    # Migrate existing widgets from Dashboard.config JSONB to widgets table
    # Uses raw SQL with JSON functions for reliability
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        INSERT INTO widgets (dashboard_id, team_id, type, title, description, query, position_x, position_y, size_w, size_h)
        SELECT
            d.id as dashboard_id,
            d.team_id,
            COALESCE(w->>'type', 'bar_chart') as type,
            COALESCE(w->'display'->>'title', 'Untitled') as title,
            w->'display'->>'description' as description,
            COALESCE(w->'query', '{}'::jsonb) as query,
            COALESCE((w->'position'->>'x')::int, 0) as position_x,
            COALESCE((w->'position'->>'y')::int, 0) as position_y,
            COALESCE((w->'size'->>'w')::int, 1) as size_w,
            COALESCE((w->'size'->>'h')::int, 1) as size_h
        FROM dashboards d,
             jsonb_array_elements(COALESCE(d.config->'widgets', '[]'::jsonb)) as w
        WHERE jsonb_array_length(COALESCE(d.config->'widgets', '[]'::jsonb)) > 0
    """)
    )

    # Clear widgets from config JSONB (keep other config data)
    connection.execute(
        sa.text("""
        UPDATE dashboards
        SET config = config - 'widgets'
        WHERE config ? 'widgets'
    """)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_widgets_team_id"), table_name="widgets")
    op.drop_index(op.f("ix_widgets_deleted_at"), table_name="widgets")
    op.drop_index(op.f("ix_widgets_dashboard_id"), table_name="widgets")
    op.drop_table("widgets")
    # ### end Alembic commands ###
