"""make message user_id nullable for system messages

Revision ID: baa8f83b7f5a
Revises: 1991909290ec
Create Date: 2025-10-24 09:43:16.872700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "baa8f83b7f5a"
down_revision: Union[str, Sequence[str], None] = "1991909290ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
