"""object platform models

Revision ID: bd79306238c3
Revises: f4532b19ba66
Create Date: 2025-09-27 15:29:59.681819

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bd79306238c3"
down_revision: str | Sequence[str] | None = "f4532b19ba66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
