"""saved-views

Revision ID: c0ef6cda2b49
Revises: 04296f2f1a16
Create Date: 2025-12-27 14:01:38.587583

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "c0ef6cda2b49"
down_revision: Union[str, Sequence[str], None] = "04296f2f1a16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_views",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("schema_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("user_id", SqidType(), nullable=True),
        sa.Column("team_id", SqidType(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "user_id", "object_type", "name", name="unique_view_name_per_owner_and_object"),
    )
    op.create_index(op.f("ix_saved_views_deleted_at"), "saved_views", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_saved_views_is_default"), "saved_views", ["is_default"], unique=False)
    op.create_index(op.f("ix_saved_views_name"), "saved_views", ["name"], unique=False)
    op.create_index(op.f("ix_saved_views_object_type"), "saved_views", ["object_type"], unique=False)
    op.create_index(
        "ix_saved_views_one_default_per_user_object",
        "saved_views",
        ["user_id", "object_type"],
        unique=True,
        postgresql_where=sa.text("is_default = true AND user_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_saved_views_team_id"), "saved_views", ["team_id"], unique=False)
    op.create_index("ix_saved_views_team_object", "saved_views", ["team_id", "object_type"], unique=False)
    op.create_index(op.f("ix_saved_views_user_id"), "saved_views", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_views_user_id"), table_name="saved_views")
    op.drop_index("ix_saved_views_team_object", table_name="saved_views")
    op.drop_index(op.f("ix_saved_views_team_id"), table_name="saved_views")
    op.drop_index(
        "ix_saved_views_one_default_per_user_object",
        table_name="saved_views",
        postgresql_where=sa.text("is_default = true AND user_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_saved_views_object_type"), table_name="saved_views")
    op.drop_index(op.f("ix_saved_views_name"), table_name="saved_views")
    op.drop_index(op.f("ix_saved_views_is_default"), table_name="saved_views")
    op.drop_index(op.f("ix_saved_views_deleted_at"), table_name="saved_views")
    op.drop_table("saved_views")
    # ### end Alembic commands ###
