"""add_null_checks_to_rls_policies

Revision ID: dffe5d0201e5
Revises: 503265b522c9
Create Date: 2025-11-16 15:36:09.637882

This migration adds explicit NULL checks to RLS policies to prevent unintended access
when RLS session variables are not set. This is a critical security fix.

Changes:
1. Update team_scope_policy to check current_setting IS NOT NULL before casting to int
2. Update dual_scope_policy to check current_setting IS NOT NULL before casting to int
3. Drop unused error_message columns from email tables

Security Impact:
- Before: When app.team_id was NULL, cast to ::int could succeed in some cases
- After: Explicit NULL check ensures no access when RLS context is not set
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dffe5d0201e5"
down_revision: Union[str, Sequence[str], None] = "503265b522c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Tables with team_scope_policy (team_id only)
TEAM_SCOPED_TABLES = [
    "campaigns",
    "brands",
    "brand_contacts",
    "roster",
    "threads",
]

# Tables with dual_scope_policy (both team_id and campaign_id)
DUAL_SCOPED_TABLES = [
    "invoices",
    "deliverables",
    "messages",
    "media",
    "deliverable_media",
    "documents",
]


def upgrade() -> None:
    """Upgrade schema."""
    # Update team_scope_policy with NULL checks
    for table in TEAM_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS team_scope_policy ON {table}")
        op.execute(
            f"""
            CREATE POLICY team_scope_policy ON {table}
            AS PERMISSIVE
            FOR ALL
            USING (
                (current_setting('app.team_id', true) IS NOT NULL
                 AND team_id = current_setting('app.team_id', true)::int)
                OR current_setting('app.is_system_mode', true)::boolean IS TRUE
            )
        """
        )

    # Update dual_scope_policy with NULL checks
    for table in DUAL_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS dual_scope_policy ON {table}")
        op.execute(
            f"""
            CREATE POLICY dual_scope_policy ON {table}
            AS PERMISSIVE
            FOR ALL
            USING (
                (current_setting('app.team_id', true) IS NOT NULL
                 AND team_id = current_setting('app.team_id', true)::int)
                OR (current_setting('app.campaign_id', true) IS NOT NULL
                    AND campaign_id = current_setting('app.campaign_id', true)::int)
                OR (current_setting('app.is_system_mode', true)::boolean IS TRUE)
            )
        """
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_messages", "error_message")
    op.drop_column("inbound_emails", "error_message")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Restore old policies without NULL checks
    for table in TEAM_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS team_scope_policy ON {table}")
        op.execute(
            f"""
            CREATE POLICY team_scope_policy ON {table}
            AS PERMISSIVE
            FOR ALL
            USING (
                team_id = current_setting('app.team_id', true)::int
                OR current_setting('app.is_system_mode', true)::boolean IS TRUE
            )
        """
        )

    for table in DUAL_SCOPED_TABLES:
        op.execute(f"DROP POLICY IF EXISTS dual_scope_policy ON {table}")
        op.execute(
            f"""
            CREATE POLICY dual_scope_policy ON {table}
            AS PERMISSIVE
            FOR ALL
            USING (
                (team_id = current_setting('app.team_id', true)::int)
                OR (campaign_id = current_setting('app.campaign_id', true)::int)
                OR (current_setting('app.is_system_mode', true)::boolean IS TRUE)
            )
        """
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("inbound_emails", sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("email_messages", sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
