"""Simplify dashboard model for RLS

Revision ID: e9279ec998bb
Revises: 13a5281c9181
Create Date: 2025-11-24 18:07:22.800400

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.state_machine.models import TextEnum
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "e9279ec998bb"
down_revision: Union[str, Sequence[str], None] = "13a5281c9181"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the old check constraint before modifying columns
    op.drop_constraint("check_owner_type_matches", "dashboards", type_="check")

    op.alter_column("dashboards", "team_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(op.f("ix_dashboards_owner_type"), table_name="dashboards")
    op.drop_constraint(op.f("unique_team_dashboard_name"), "dashboards", type_="unique")
    op.drop_constraint(op.f("unique_user_dashboard_name"), "dashboards", type_="unique")
    op.create_unique_constraint("unique_dashboard_name_per_owner", "dashboards", ["team_id", "user_id", "name"])
    op.drop_constraint(op.f("dashboards_team_id_fkey"), "dashboards", type_="foreignkey")
    op.create_foreign_key(None, "dashboards", "teams", ["team_id"], ["id"], ondelete="RESTRICT")
    op.drop_column("dashboards", "owner_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dashboards", sa.Column("owner_type", sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, "dashboards", type_="foreignkey")
    op.create_foreign_key(
        op.f("dashboards_team_id_fkey"), "dashboards", "teams", ["team_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("unique_dashboard_name_per_owner", "dashboards", type_="unique")
    op.create_unique_constraint(
        op.f("unique_user_dashboard_name"), "dashboards", ["user_id", "name"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("unique_team_dashboard_name"), "dashboards", ["team_id", "name"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("ix_dashboards_owner_type"), "dashboards", ["owner_type"], unique=False)
    op.alter_column("dashboards", "team_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
