"""enable_rls_and_create_policies

Revision ID: f9c74c321a3f
Revises: fa9121fbce6b
Create Date: 2025-10-19 16:04:40.361062

This migration enables PostgreSQL Row-Level Security (RLS) on all scoped tables.
The actual RLS policies are auto-generated by alembic-utils from the RLSMixin factory.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9c74c321a3f"
down_revision: Union[str, Sequence[str], None] = "fa9121fbce6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Tables with RLS (team-scoped and dual-scoped)
RLS_TABLES = [
    "brands",
    "brand_contacts",
    "campaigns",
    "roster",
    "posts",
    "invoices",
    "media",
]


def upgrade() -> None:
    """Enable RLS on all scoped tables."""
    for table in RLS_TABLES:
        # Enable Row-Level Security
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")

        # Force RLS even for table owner (important for security!)
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")

    # Policies are auto-created by alembic-utils from RLS_POLICY_REGISTRY
    # See app/base/scope_mixins.py and alembic/env.py


def downgrade() -> None:
    """Disable RLS on all scoped tables."""
    for table in RLS_TABLES:
        # Policies are auto-dropped by alembic-utils

        # Disable Row-Level Security
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
