/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ManagerLab
 * Private schema of ManagerLab with Scalar OpenAPI docs
 * OpenAPI spec version: 0.0.1
 */
export type ActionDTOIcon = string | null;

export type ActionDTOConfirmationMessage = string | null;

export interface ActionDTO {
  action: string;
  label: string;
  is_bulk_allowed?: boolean;
  available?: boolean;
  priority?: number;
  icon?: ActionDTOIcon;
  confirmation_message?: ActionDTOConfirmationMessage;
}

export type ActionExecutionResponseResults = {[key: string]: unknown};

export interface ActionExecutionResponse {
  success: boolean;
  message: string;
  results?: ActionExecutionResponseResults;
}

/**
 * Types of action groups.
 */
export type ActionGroupType = typeof ActionGroupType[keyof typeof ActionGroupType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionGroupType = {
  media_actions: 'media_actions',
  top_level_media_actions: 'top_level_media_actions',
  post_actions: 'post_actions',
  top_level_post_actions: 'top_level_post_actions',
  brand_actions: 'brand_actions',
  campaign_actions: 'campaign_actions',
  top_level_campaign_actions: 'top_level_campaign_actions',
  invoice_actions: 'invoice_actions',
  top_level_invoice_actions: 'top_level_invoice_actions',
} as const;

export interface ActionListResponse {
  actions: ActionDTO[];
}

export type AddUserToWaitlistWaitlistEntryResponseBodyCompany = string | null;

export type AddUserToWaitlistWaitlistEntryResponseBodyMessage = string | null;

export interface AddUserToWaitlistWaitlistEntryResponseBody {
  name: string;
  email: string;
  company?: AddUserToWaitlistWaitlistEntryResponseBodyCompany;
  message?: AddUserToWaitlistWaitlistEntryResponseBodyMessage;
  id: number;
  created_at: string;
  updated_at: string;
  public_id: string;
}

export interface BoolFieldValue {
  value: boolean;
  type: 'bool';
}

export interface BooleanFilterDefinition {
  column: string;
  value: boolean;
  type: 'boolean_filter';
}

export type ColumnDefinitionDTOAvailableValues = string[] | null;

export interface ColumnDefinitionDTO {
  key: string;
  label: string;
  type: FieldType;
  filter_type: FilterType;
  sortable?: boolean;
  default_visible?: boolean;
  available_values?: ColumnDefinitionDTOAvailableValues;
}

export type CompensationStructure = typeof CompensationStructure[keyof typeof CompensationStructure];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompensationStructure = {
  flat_fee: 'flat_fee',
  per_deliverable: 'per_deliverable',
  performance_based: 'performance_based',
} as const;

export interface CreateCampaignAction {
  data: AppCampaignsRoutesCampaignCreateDTOSchema;
  action: 'top_level_campaign_actions__campaign_create';
}

export interface CreateInvoiceAction {
  data: AppPaymentsSchemasInvoiceCreateDTOSchema;
  action: 'top_level_invoice_actions__invoice_create';
}

export interface CreateMediaAction {
  data: AppMediaSchemasMediaCreateDTOSchema;
  action: 'top_level_media_actions__top_level_media_create';
}

export interface CreatePostAction {
  data: AppPostsSchemasPostCreateDTOSchema;
  action: 'top_level_post_actions__top_level_post_create';
}

export interface CreateUserSchema {
  name: string;
  email: string;
}

export interface CreateUserUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface DateFieldValue {
  value: string;
  type: 'date';
}

export type DateFilterDefinitionStart = string | null;

export type DateFilterDefinitionFinish = string | null;

export interface DateFilterDefinition {
  column: string;
  start?: DateFilterDefinitionStart;
  finish?: DateFilterDefinitionFinish;
  type: 'date_filter';
}

export interface DatetimeFieldValue {
  value: string;
  type: 'datetime';
}

export interface EmailFieldValue {
  value: string;
  type: 'email';
}

export interface EnumFieldValue {
  value: string;
  type: 'enum';
}

export interface EnumFilterDefinition {
  column: string;
  values: string[];
  type: 'enum_filter';
}

/**
 * Field types for object fields.
 */
export type FieldType = typeof FieldType[keyof typeof FieldType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FieldType = {
  string: 'string',
  int: 'int',
  float: 'float',
  enum: 'enum',
  bool: 'bool',
  date: 'date',
  datetime: 'datetime',
  usd: 'usd',
  email: 'email',
  url: 'url',
  text: 'text',
  image: 'image',
} as const;

/**
 * Available filter types for different field types.
 */
export type FilterType = typeof FilterType[keyof typeof FilterType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilterType = {
  text_filter: 'text_filter',
  range_filter: 'range_filter',
  date_filter: 'date_filter',
  boolean_filter: 'boolean_filter',
  enum_filter: 'enum_filter',
} as const;

export interface FloatFieldValue {
  value: number;
  type: 'float';
}

export type GetBrandBrandResponseBodyDescription = string | null;

export type GetBrandBrandResponseBodyToneOfVoice = string | null;

export type GetBrandBrandResponseBodyBrandValues = string | null;

export type GetBrandBrandResponseBodyTargetAudience = string | null;

export type GetBrandBrandResponseBodyWebsite = string | null;

export type GetBrandBrandResponseBodyEmail = string | null;

export type GetBrandBrandResponseBodyPhone = string | null;

export type GetBrandBrandResponseBodyNotes = string | null;

export interface GetBrandBrandResponseBody {
  name: string;
  description?: GetBrandBrandResponseBodyDescription;
  tone_of_voice?: GetBrandBrandResponseBodyToneOfVoice;
  brand_values?: GetBrandBrandResponseBodyBrandValues;
  target_audience?: GetBrandBrandResponseBodyTargetAudience;
  website?: GetBrandBrandResponseBodyWebsite;
  email?: GetBrandBrandResponseBodyEmail;
  phone?: GetBrandBrandResponseBodyPhone;
  notes?: GetBrandBrandResponseBodyNotes;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GetBrandContactBrandContactResponseBodyEmail = string | null;

export type GetBrandContactBrandContactResponseBodyPhone = string | null;

export type GetBrandContactBrandContactResponseBodyNotes = string | null;

export interface GetBrandContactBrandContactResponseBody {
  first_name: string;
  last_name: string;
  email?: GetBrandContactBrandContactResponseBodyEmail;
  phone?: GetBrandContactBrandContactResponseBodyPhone;
  notes?: GetBrandContactBrandContactResponseBodyNotes;
  brand_id: number;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GetCampaignCampaignResponseBodyDescription = string | null;

export interface GetCampaignCampaignResponseBody {
  name: string;
  description?: GetCampaignCampaignResponseBodyDescription;
  brand_id: number;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface GetCurrentUserUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GetInvoiceInvoiceResponseBodyDescription = string | null;

export type GetInvoiceInvoiceResponseBodyNotes = string | null;

export type GetInvoiceInvoiceResponseBodyCampaignId = number | null;

export interface GetInvoiceInvoiceResponseBody {
  invoice_number: number;
  customer_name: string;
  customer_email: string;
  posting_date: string;
  due_date: string;
  amount_due: number;
  amount_paid?: number;
  description?: GetInvoiceInvoiceResponseBodyDescription;
  notes?: GetInvoiceInvoiceResponseBodyNotes;
  campaign_id?: GetInvoiceInvoiceResponseBodyCampaignId;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GetPostPostResponseBodyContent = string | null;

export type GetPostPostResponseBodyNotes = {[key: string]: unknown};

export type GetPostPostResponseBodyCampaignId = number | null;

export interface GetPostPostResponseBody {
  title: string;
  content?: GetPostPostResponseBodyContent;
  platforms: SocialMediaPlatforms;
  posting_date: string;
  notes: GetPostPostResponseBodyNotes;
  compensation_structure?: CompensationStructure;
  campaign_id?: GetPostPostResponseBodyCampaignId;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface GetUserUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GoogleUserInfoResponseSchemaPicture = string | null;

export interface GoogleUserInfoResponseSchema {
  google_id: string;
  email: string;
  name: string;
  picture?: GoogleUserInfoResponseSchemaPicture;
  user_id: number;
}

export type ImageFieldValueThumbnailUrl = string | null;

export interface ImageFieldValue {
  url: string;
  thumbnail_url?: ImageFieldValueThumbnailUrl;
  type: 'image';
}

export interface IntFieldValue {
  value: number;
  type: 'int';
}

export interface ListUsersUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  created_at: string;
  updated_at: string;
  id: string;
}

export type ObjectDetailDTOChildrenItem = {[key: string]: ObjectRelationDTO};

export type ObjectDetailDTOParentsItem = {[key: string]: ObjectRelationDTO};

export interface ObjectDetailDTO {
  id: string;
  object_type: string;
  state: string;
  title: string;
  fields: ObjectFieldDTO[];
  actions: ActionDTO[];
  created_at: string;
  updated_at: string;
  children?: ObjectDetailDTOChildrenItem[];
  parents?: ObjectDetailDTOParentsItem[];
}

export type ObjectFieldDTOValue = StringFieldValue | IntFieldValue | FloatFieldValue | BoolFieldValue | EnumFieldValue | DateFieldValue | DatetimeFieldValue | USDFieldValue | EmailFieldValue | URLFieldValue | TextFieldValue | ImageFieldValue;

export type ObjectFieldDTOLabel = string | null;

export interface ObjectFieldDTO {
  key: string;
  value: ObjectFieldDTOValue;
  label?: ObjectFieldDTOLabel;
  editable?: boolean;
}

export type ObjectListDTOSubtitle = string | null;

export type ObjectListDTOLink = string | null;

export interface ObjectListDTO {
  id: string;
  object_type: string;
  title: string;
  state: string;
  created_at: string;
  updated_at: string;
  subtitle?: ObjectListDTOSubtitle;
  actions?: ActionDTO[];
  fields?: ObjectFieldDTO[];
  link?: ObjectListDTOLink;
}

export type ObjectListRequestFiltersItem = TextFilterDefinition | RangeFilterDefinition | DateFilterDefinition | BooleanFilterDefinition | EnumFilterDefinition;

export type ObjectListRequestSearch = string | null;

export type ObjectListRequestColumn = string[] | null;

export interface ObjectListRequest {
  limit?: number;
  offset?: number;
  filters?: ObjectListRequestFiltersItem[];
  sorts?: SortDefinition[];
  search?: ObjectListRequestSearch;
  column?: ObjectListRequestColumn;
}

export interface ObjectListResponse {
  objects: ObjectListDTO[];
  total: number;
  limit: number;
  offset: number;
  columns: ColumnDefinitionDTO[];
  actions?: ActionDTO[];
}

export interface ObjectRelationDTO {
  object_type: string;
  sqid: string;
  title: string;
}

export type ObjectTypes = typeof ObjectTypes[keyof typeof ObjectTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObjectTypes = {
  users: 'users',
  roster: 'roster',
  brands: 'brands',
  brandcontacts: 'brandcontacts',
  campaigns: 'campaigns',
  posts: 'posts',
  media: 'media',
  invoices: 'invoices',
} as const;

export interface PresignedUploadRequestSchema {
  file_name: string;
  content_type: string;
  file_size: number;
}

export interface PresignedUploadResponseSchema {
  upload_url: string;
  file_key: string;
}

export type RangeFilterDefinitionStart = number | number | null;

export type RangeFilterDefinitionFinish = number | number | null;

export interface RangeFilterDefinition {
  column: string;
  start?: RangeFilterDefinitionStart;
  finish?: RangeFilterDefinitionFinish;
  type: 'range_filter';
}

export interface RegisterMediaMediaResponseBody {
  file_name: string;
  file_type: string;
  file_size: number;
  mime_type: string;
  status?: string;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface RegisterMediaSchema {
  file_key: string;
  file_name: string;
  file_size: number;
  mime_type: string;
}

export type SocialMediaPlatforms = typeof SocialMediaPlatforms[keyof typeof SocialMediaPlatforms];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SocialMediaPlatforms = {
  instagram: 'instagram',
  facebook: 'facebook',
  tiktok: 'tiktok',
  youtube: 'youtube',
} as const;

export interface SortDefinition {
  column: string;
  direction: SortDirection;
}

/**
 * Sort direction options.
 */
export type SortDirection = typeof SortDirection[keyof typeof SortDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortDirection = {
  sort_asc: 'sort_asc',
  sort_desc: 'sort_desc',
} as const;

export interface StringFieldValue {
  value: string;
  type: 'string';
}

export interface TextFieldValue {
  value: string;
  type: 'text';
}

export type TextFilterDefinitionOperation = typeof TextFilterDefinitionOperation[keyof typeof TextFilterDefinitionOperation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TextFilterDefinitionOperation = {
  contains: 'contains',
  starts_with: 'starts_with',
  ends_with: 'ends_with',
  equals: 'equals',
} as const;

export interface TextFilterDefinition {
  column: string;
  operation: TextFilterDefinitionOperation;
  value: string;
  type: 'text_filter';
}

export interface URLFieldValue {
  value: string;
  type: 'url';
}

export interface USDFieldValue {
  value: number;
  type: 'usd';
}

export type UpdateBrandBrandResponseBodyDescription = string | null;

export type UpdateBrandBrandResponseBodyToneOfVoice = string | null;

export type UpdateBrandBrandResponseBodyBrandValues = string | null;

export type UpdateBrandBrandResponseBodyTargetAudience = string | null;

export type UpdateBrandBrandResponseBodyWebsite = string | null;

export type UpdateBrandBrandResponseBodyEmail = string | null;

export type UpdateBrandBrandResponseBodyPhone = string | null;

export type UpdateBrandBrandResponseBodyNotes = string | null;

export interface UpdateBrandBrandResponseBody {
  name: string;
  description?: UpdateBrandBrandResponseBodyDescription;
  tone_of_voice?: UpdateBrandBrandResponseBodyToneOfVoice;
  brand_values?: UpdateBrandBrandResponseBodyBrandValues;
  target_audience?: UpdateBrandBrandResponseBodyTargetAudience;
  website?: UpdateBrandBrandResponseBodyWebsite;
  email?: UpdateBrandBrandResponseBodyEmail;
  phone?: UpdateBrandBrandResponseBodyPhone;
  notes?: UpdateBrandBrandResponseBodyNotes;
  created_at: string;
  updated_at: string;
  id: string;
}

export type UpdateBrandContactBrandContactResponseBodyEmail = string | null;

export type UpdateBrandContactBrandContactResponseBodyPhone = string | null;

export type UpdateBrandContactBrandContactResponseBodyNotes = string | null;

export interface UpdateBrandContactBrandContactResponseBody {
  first_name: string;
  last_name: string;
  email?: UpdateBrandContactBrandContactResponseBodyEmail;
  phone?: UpdateBrandContactBrandContactResponseBodyPhone;
  notes?: UpdateBrandContactBrandContactResponseBodyNotes;
  brand_id: number;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface UpdateCampaignAction {
  data: AppCampaignsRoutesCampaignUpdateDTOSchema;
  action: 'campaign_actions__campaign_update';
}

export type UpdateCampaignCampaignResponseBodyDescription = string | null;

export interface UpdateCampaignCampaignResponseBody {
  name: string;
  description?: UpdateCampaignCampaignResponseBodyDescription;
  brand_id: number;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface UpdateInvoiceAction {
  data: AppPaymentsSchemasInvoiceUpdateDTOSchema;
  action: 'invoice_actions__invoice_update';
}

export type UpdateInvoiceInvoiceResponseBodyDescription = string | null;

export type UpdateInvoiceInvoiceResponseBodyNotes = string | null;

export type UpdateInvoiceInvoiceResponseBodyCampaignId = number | null;

export interface UpdateInvoiceInvoiceResponseBody {
  invoice_number: number;
  customer_name: string;
  customer_email: string;
  posting_date: string;
  due_date: string;
  amount_due: number;
  amount_paid?: number;
  description?: UpdateInvoiceInvoiceResponseBodyDescription;
  notes?: UpdateInvoiceInvoiceResponseBodyNotes;
  campaign_id?: UpdateInvoiceInvoiceResponseBodyCampaignId;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface UpdateMediaAction {
  data: AppMediaSchemasMediaUpdateDTOSchema;
  action: 'media_actions__media_update';
}

export interface UpdatePostAction {
  data: AppPostsSchemasPostUpdateDTOSchema;
  action: 'post_actions__post_update';
}

export type UpdatePostPostResponseBodyContent = string | null;

export type UpdatePostPostResponseBodyNotes = {[key: string]: unknown};

export type UpdatePostPostResponseBodyCampaignId = number | null;

export interface UpdatePostPostResponseBody {
  title: string;
  content?: UpdatePostPostResponseBodyContent;
  platforms: SocialMediaPlatforms;
  posting_date: string;
  notes: UpdatePostPostResponseBodyNotes;
  compensation_structure?: CompensationStructure;
  campaign_id?: UpdatePostPostResponseBodyCampaignId;
  created_at: string;
  updated_at: string;
  id: string;
}

export type UserWaitlistFormSchemaCompany = string | null;

export type UserWaitlistFormSchemaMessage = string | null;

export interface UserWaitlistFormSchema {
  name: string;
  email: string;
  company?: UserWaitlistFormSchemaCompany;
  message?: UserWaitlistFormSchemaMessage;
}

export type AppCampaignsRoutesCampaignCreateDTOSchemaDescription = string | null;

export interface AppCampaignsRoutesCampaignCreateDTOSchema {
  name: string;
  description?: AppCampaignsRoutesCampaignCreateDTOSchemaDescription;
  brand_id: number;
  state: string;
}

export type AppCampaignsRoutesCampaignUpdateDTOSchemaDescription = string | null;

export interface AppCampaignsRoutesCampaignUpdateDTOSchema {
  name: string;
  description?: AppCampaignsRoutesCampaignUpdateDTOSchemaDescription;
  brand_id: number;
  state: string;
}

export interface AppMediaSchemasMediaCreateDTOSchema {
  file_name: string;
  file_type: string;
  file_size: number;
  mime_type: string;
  status: string;
}

export interface AppMediaSchemasMediaUpdateDTOSchema {
  file_name: string;
  file_type: string;
  file_size: number;
  mime_type: string;
  status: string;
}

export type AppPaymentsSchemasInvoiceCreateDTOSchemaDescription = string | null;

export type AppPaymentsSchemasInvoiceCreateDTOSchemaNotes = string | null;

export type AppPaymentsSchemasInvoiceCreateDTOSchemaCampaignId = number | null;

export interface AppPaymentsSchemasInvoiceCreateDTOSchema {
  invoice_number: number;
  customer_name: string;
  customer_email: string;
  posting_date: string;
  due_date: string;
  amount_due: number;
  amount_paid: number;
  description?: AppPaymentsSchemasInvoiceCreateDTOSchemaDescription;
  notes?: AppPaymentsSchemasInvoiceCreateDTOSchemaNotes;
  campaign_id?: AppPaymentsSchemasInvoiceCreateDTOSchemaCampaignId;
  state: string;
}

export type AppPaymentsSchemasInvoiceUpdateDTOSchemaDescription = string | null;

export type AppPaymentsSchemasInvoiceUpdateDTOSchemaNotes = string | null;

export type AppPaymentsSchemasInvoiceUpdateDTOSchemaCampaignId = number | null;

export interface AppPaymentsSchemasInvoiceUpdateDTOSchema {
  invoice_number: number;
  customer_name: string;
  customer_email: string;
  posting_date: string;
  due_date: string;
  amount_due: number;
  amount_paid: number;
  description?: AppPaymentsSchemasInvoiceUpdateDTOSchemaDescription;
  notes?: AppPaymentsSchemasInvoiceUpdateDTOSchemaNotes;
  campaign_id?: AppPaymentsSchemasInvoiceUpdateDTOSchemaCampaignId;
  state: string;
}

export type AppPostsSchemasPostCreateDTOSchemaContent = string | null;

export type AppPostsSchemasPostCreateDTOSchemaCompensationStructure = string | null;

export type AppPostsSchemasPostCreateDTOSchemaCampaignId = number | null;

export interface AppPostsSchemasPostCreateDTOSchema {
  title: string;
  content?: AppPostsSchemasPostCreateDTOSchemaContent;
  platforms: string;
  posting_date: string;
  notes: unknown;
  compensation_structure?: AppPostsSchemasPostCreateDTOSchemaCompensationStructure;
  campaign_id?: AppPostsSchemasPostCreateDTOSchemaCampaignId;
  state: string;
  created_at: string;
  updated_at: string;
}

export type AppPostsSchemasPostUpdateDTOSchemaContent = string | null;

export type AppPostsSchemasPostUpdateDTOSchemaCompensationStructure = string | null;

export type AppPostsSchemasPostUpdateDTOSchemaCampaignId = number | null;

export interface AppPostsSchemasPostUpdateDTOSchema {
  title: string;
  content?: AppPostsSchemasPostUpdateDTOSchemaContent;
  platforms: string;
  posting_date: string;
  notes: unknown;
  compensation_structure?: AppPostsSchemasPostUpdateDTOSchemaCompensationStructure;
  campaign_id?: AppPostsSchemasPostUpdateDTOSchemaCampaignId;
  state: string;
}

export type HealthHealthCheck200 = { [key: string]: unknown };

export type UsersSignupAddUserToWaitlist400ExtraAnyOf = {[key: string]: unknown};

export type UsersSignupAddUserToWaitlist400Extra = null | UsersSignupAddUserToWaitlist400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type UsersSignupAddUserToWaitlist400 = {
  status_code: number;
  detail: string;
  extra?: UsersSignupAddUserToWaitlist400Extra;
};

export type UsersCreateUser400ExtraAnyOf = {[key: string]: unknown};

export type UsersCreateUser400Extra = null | UsersCreateUser400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type UsersCreateUser400 = {
  status_code: number;
  detail: string;
  extra?: UsersCreateUser400Extra;
};

export type UsersUserIdGetUser400ExtraAnyOf = {[key: string]: unknown};

export type UsersUserIdGetUser400Extra = null | UsersUserIdGetUser400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type UsersUserIdGetUser400 = {
  status_code: number;
  detail: string;
  extra?: UsersUserIdGetUser400Extra;
};

export type AuthGoogleLoginGoogleLogin200 = { [key: string]: unknown };

export type AuthGoogleCallbackGoogleCallbackParams = {
code?: string | null;
state?: string | null;
error?: string | null;
};

export type AuthGoogleCallbackGoogleCallback200 = { [key: string]: unknown };

export type AuthGoogleCallbackGoogleCallback400ExtraAnyOf = {[key: string]: unknown};

export type AuthGoogleCallbackGoogleCallback400Extra = null | AuthGoogleCallbackGoogleCallback400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type AuthGoogleCallbackGoogleCallback400 = {
  status_code: number;
  detail: string;
  extra?: AuthGoogleCallbackGoogleCallback400Extra;
};

export type OObjectTypeIdGetObjectDetail400ExtraAnyOf = {[key: string]: unknown};

export type OObjectTypeIdGetObjectDetail400Extra = null | OObjectTypeIdGetObjectDetail400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type OObjectTypeIdGetObjectDetail400 = {
  status_code: number;
  detail: string;
  extra?: OObjectTypeIdGetObjectDetail400Extra;
};

export type ListObjects400ExtraAnyOf = {[key: string]: unknown};

export type ListObjects400Extra = null | ListObjects400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type ListObjects400 = {
  status_code: number;
  detail: string;
  extra?: ListObjects400Extra;
};

export type ActionsActionGroupListActions400ExtraAnyOf = {[key: string]: unknown};

export type ActionsActionGroupListActions400Extra = null | ActionsActionGroupListActions400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type ActionsActionGroupListActions400 = {
  status_code: number;
  detail: string;
  extra?: ActionsActionGroupListActions400Extra;
};

export type ActionsActionGroupExecuteActionBody = UpdateInvoiceAction | UpdatePostAction | UpdateCampaignAction | UpdateMediaAction | CreateInvoiceAction | CreatePostAction | CreateCampaignAction | CreateMediaAction;

export type ActionsActionGroupExecuteAction400ExtraAnyOf = {[key: string]: unknown};

export type ActionsActionGroupExecuteAction400Extra = null | ActionsActionGroupExecuteAction400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type ActionsActionGroupExecuteAction400 = {
  status_code: number;
  detail: string;
  extra?: ActionsActionGroupExecuteAction400Extra;
};

export type ActionsActionGroupObjectIdListObjectActions400ExtraAnyOf = {[key: string]: unknown};

export type ActionsActionGroupObjectIdListObjectActions400Extra = null | ActionsActionGroupObjectIdListObjectActions400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type ActionsActionGroupObjectIdListObjectActions400 = {
  status_code: number;
  detail: string;
  extra?: ActionsActionGroupObjectIdListObjectActions400Extra;
};

export type ActionsActionGroupObjectIdExecuteObjectActionBody = UpdateInvoiceAction | UpdatePostAction | UpdateCampaignAction | UpdateMediaAction | CreateInvoiceAction | CreatePostAction | CreateCampaignAction | CreateMediaAction;

export type ActionsActionGroupObjectIdExecuteObjectAction400ExtraAnyOf = {[key: string]: unknown};

export type ActionsActionGroupObjectIdExecuteObjectAction400Extra = null | ActionsActionGroupObjectIdExecuteObjectAction400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type ActionsActionGroupObjectIdExecuteObjectAction400 = {
  status_code: number;
  detail: string;
  extra?: ActionsActionGroupObjectIdExecuteObjectAction400Extra;
};

export type BrandsIdGetBrand400ExtraAnyOf = {[key: string]: unknown};

export type BrandsIdGetBrand400Extra = null | BrandsIdGetBrand400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type BrandsIdGetBrand400 = {
  status_code: number;
  detail: string;
  extra?: BrandsIdGetBrand400Extra;
};

export type BrandsIdUpdateBrand400ExtraAnyOf = {[key: string]: unknown};

export type BrandsIdUpdateBrand400Extra = null | BrandsIdUpdateBrand400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type BrandsIdUpdateBrand400 = {
  status_code: number;
  detail: string;
  extra?: BrandsIdUpdateBrand400Extra;
};

export type BrandsContactsIdGetBrandContact400ExtraAnyOf = {[key: string]: unknown};

export type BrandsContactsIdGetBrandContact400Extra = null | BrandsContactsIdGetBrandContact400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type BrandsContactsIdGetBrandContact400 = {
  status_code: number;
  detail: string;
  extra?: BrandsContactsIdGetBrandContact400Extra;
};

export type BrandsContactsIdUpdateBrandContact400ExtraAnyOf = {[key: string]: unknown};

export type BrandsContactsIdUpdateBrandContact400Extra = null | BrandsContactsIdUpdateBrandContact400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type BrandsContactsIdUpdateBrandContact400 = {
  status_code: number;
  detail: string;
  extra?: BrandsContactsIdUpdateBrandContact400Extra;
};

export type CampaignsIdGetCampaign400ExtraAnyOf = {[key: string]: unknown};

export type CampaignsIdGetCampaign400Extra = null | CampaignsIdGetCampaign400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type CampaignsIdGetCampaign400 = {
  status_code: number;
  detail: string;
  extra?: CampaignsIdGetCampaign400Extra;
};

export type CampaignsIdUpdateCampaign400ExtraAnyOf = {[key: string]: unknown};

export type CampaignsIdUpdateCampaign400Extra = null | CampaignsIdUpdateCampaign400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type CampaignsIdUpdateCampaign400 = {
  status_code: number;
  detail: string;
  extra?: CampaignsIdUpdateCampaign400Extra;
};

export type PostsIdGetPost400ExtraAnyOf = {[key: string]: unknown};

export type PostsIdGetPost400Extra = null | PostsIdGetPost400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type PostsIdGetPost400 = {
  status_code: number;
  detail: string;
  extra?: PostsIdGetPost400Extra;
};

export type PostsIdUpdatePost400ExtraAnyOf = {[key: string]: unknown};

export type PostsIdUpdatePost400Extra = null | PostsIdUpdatePost400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type PostsIdUpdatePost400 = {
  status_code: number;
  detail: string;
  extra?: PostsIdUpdatePost400Extra;
};

export type MediaPresignedUploadRequestPresignedUpload400ExtraAnyOf = {[key: string]: unknown};

export type MediaPresignedUploadRequestPresignedUpload400Extra = null | MediaPresignedUploadRequestPresignedUpload400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type MediaPresignedUploadRequestPresignedUpload400 = {
  status_code: number;
  detail: string;
  extra?: MediaPresignedUploadRequestPresignedUpload400Extra;
};

export type MediaRegisterRegisterMedia400ExtraAnyOf = {[key: string]: unknown};

export type MediaRegisterRegisterMedia400Extra = null | MediaRegisterRegisterMedia400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type MediaRegisterRegisterMedia400 = {
  status_code: number;
  detail: string;
  extra?: MediaRegisterRegisterMedia400Extra;
};

export type MediaIdDeleteMedia200 = {[key: string]: string};

export type MediaIdDeleteMedia400ExtraAnyOf = {[key: string]: unknown};

export type MediaIdDeleteMedia400Extra = null | MediaIdDeleteMedia400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type MediaIdDeleteMedia400 = {
  status_code: number;
  detail: string;
  extra?: MediaIdDeleteMedia400Extra;
};

export type InvoicesIdGetInvoice400ExtraAnyOf = {[key: string]: unknown};

export type InvoicesIdGetInvoice400Extra = null | InvoicesIdGetInvoice400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type InvoicesIdGetInvoice400 = {
  status_code: number;
  detail: string;
  extra?: InvoicesIdGetInvoice400Extra;
};

export type InvoicesIdUpdateInvoice400ExtraAnyOf = {[key: string]: unknown};

export type InvoicesIdUpdateInvoice400Extra = null | InvoicesIdUpdateInvoice400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type InvoicesIdUpdateInvoice400 = {
  status_code: number;
  detail: string;
  extra?: InvoicesIdUpdateInvoice400Extra;
};

export type LocalUploadKeyLocalUpload200 = { [key: string]: unknown };

export type LocalUploadKeyLocalUpload400ExtraAnyOf = {[key: string]: unknown};

export type LocalUploadKeyLocalUpload400Extra = null | LocalUploadKeyLocalUpload400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type LocalUploadKeyLocalUpload400 = {
  status_code: number;
  detail: string;
  extra?: LocalUploadKeyLocalUpload400Extra;
};

export type LocalDownloadKeyLocalDownload200 = { [key: string]: unknown };

export type LocalDownloadKeyLocalDownload400ExtraAnyOf = {[key: string]: unknown};

export type LocalDownloadKeyLocalDownload400Extra = null | LocalDownloadKeyLocalDownload400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type LocalDownloadKeyLocalDownload400 = {
  status_code: number;
  detail: string;
  extra?: LocalDownloadKeyLocalDownload400Extra;
};

