/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ManagerLab
 * Private schema of ManagerLab with Scalar OpenAPI docs
 * OpenAPI spec version: 0.0.1
 */
export interface ActionDTO {
  action: string;
  label: string;
  available?: boolean;
  priority?: number;
}

export type AddUserToWaitlistWaitlistEntryResponseBodyCompany = string | null;

export type AddUserToWaitlistWaitlistEntryResponseBodyMessage = string | null;

export interface AddUserToWaitlistWaitlistEntryResponseBody {
  name: string;
  email: string;
  company?: AddUserToWaitlistWaitlistEntryResponseBodyCompany;
  message?: AddUserToWaitlistWaitlistEntryResponseBodyMessage;
  id: number;
  created_at: string;
  updated_at: string;
  public_id: string;
}

export interface BooleanFilterDefinition {
  column: string;
  value: boolean;
  type: 'boolean_filter';
}

export interface ColumnDefinitionDTO {
  key: string;
  label: string;
  type: FieldType;
  sortable?: boolean;
  available_filters?: FilterType[];
  default_visible?: boolean;
}

export type CompensationStructure = typeof CompensationStructure[keyof typeof CompensationStructure];


 
export const CompensationStructure = {
  flat_fee: 'flat_fee',
  per_deliverable: 'per_deliverable',
  performance_based: 'performance_based',
} as const;

export interface CreateUserSchema {
  name: string;
  email: string;
}

export interface CreateUserUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  created_at: string;
  updated_at: string;
  id: string;
}

export type DateFilterDefinitionStart = string | null;

export type DateFilterDefinitionFinish = string | null;

export interface DateFilterDefinition {
  column: string;
  start?: DateFilterDefinitionStart;
  finish?: DateFilterDefinitionFinish;
  type: 'date_filter';
}

/**
 * Field types for object fields.
 */
export type FieldType = typeof FieldType[keyof typeof FieldType];


 
export const FieldType = {
  string: 'string',
  int: 'int',
  float: 'float',
  enum: 'enum',
  bool: 'bool',
  date: 'date',
  datetime: 'datetime',
  usd: 'usd',
  email: 'email',
  url: 'url',
  text: 'text',
} as const;

/**
 * Available filter types for different field types.
 */
export type FilterType = typeof FilterType[keyof typeof FilterType];


 
export const FilterType = {
  text_filter: 'text_filter',
  range_filter: 'range_filter',
  date_filter: 'date_filter',
  boolean_filter: 'boolean_filter',
  enum_filter: 'enum_filter',
} as const;

export type GetBrandBrandResponseBodyDescription = string | null;

export type GetBrandBrandResponseBodyToneOfVoice = string | null;

export type GetBrandBrandResponseBodyBrandValues = string | null;

export type GetBrandBrandResponseBodyTargetAudience = string | null;

export type GetBrandBrandResponseBodyWebsite = string | null;

export type GetBrandBrandResponseBodyEmail = string | null;

export type GetBrandBrandResponseBodyPhone = string | null;

export type GetBrandBrandResponseBodyNotes = string | null;

export interface GetBrandBrandResponseBody {
  name: string;
  description?: GetBrandBrandResponseBodyDescription;
  tone_of_voice?: GetBrandBrandResponseBodyToneOfVoice;
  brand_values?: GetBrandBrandResponseBodyBrandValues;
  target_audience?: GetBrandBrandResponseBodyTargetAudience;
  website?: GetBrandBrandResponseBodyWebsite;
  email?: GetBrandBrandResponseBodyEmail;
  phone?: GetBrandBrandResponseBodyPhone;
  notes?: GetBrandBrandResponseBodyNotes;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GetBrandContactBrandContactResponseBodyEmail = string | null;

export type GetBrandContactBrandContactResponseBodyPhone = string | null;

export type GetBrandContactBrandContactResponseBodyNotes = string | null;

export interface GetBrandContactBrandContactResponseBody {
  first_name: string;
  last_name: string;
  email?: GetBrandContactBrandContactResponseBodyEmail;
  phone?: GetBrandContactBrandContactResponseBodyPhone;
  notes?: GetBrandContactBrandContactResponseBodyNotes;
  brand_id: number;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GetCampaignCampaignResponseBodyDescription = string | null;

export interface GetCampaignCampaignResponseBody {
  name: string;
  description?: GetCampaignCampaignResponseBodyDescription;
  brand_id: number;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface GetCurrentUserUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GetInvoiceInvoiceResponseBodyDescription = string | null;

export type GetInvoiceInvoiceResponseBodyNotes = string | null;

export type GetInvoiceInvoiceResponseBodyCampaignId = number | null;

export interface GetInvoiceInvoiceResponseBody {
  invoice_number: number;
  customer_name: string;
  customer_email: string;
  posting_date: string;
  due_date: string;
  amount_due: number;
  amount_paid?: number;
  description?: GetInvoiceInvoiceResponseBodyDescription;
  notes?: GetInvoiceInvoiceResponseBodyNotes;
  campaign_id?: GetInvoiceInvoiceResponseBodyCampaignId;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface GetMediaMediaResponseBody {
  filename: string;
  image_link: string;
  thumnbnail_link?: string;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GetPostPostResponseBodyContent = string | null;

export type GetPostPostResponseBodyNotes = {[key: string]: unknown};

export type GetPostPostResponseBodyCampaignId = number | null;

export interface GetPostPostResponseBody {
  title: string;
  content?: GetPostPostResponseBodyContent;
  platforms: SocialMediaPlatforms;
  posting_date: string;
  notes: GetPostPostResponseBodyNotes;
  compensation_structure?: CompensationStructure;
  campaign_id?: GetPostPostResponseBodyCampaignId;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface GetUserUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  created_at: string;
  updated_at: string;
  id: string;
}

export type GoogleUserInfoResponseSchemaPicture = string | null;

export interface GoogleUserInfoResponseSchema {
  google_id: string;
  email: string;
  name: string;
  picture?: GoogleUserInfoResponseSchemaPicture;
  user_id: number;
}

export interface ListUsersUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  created_at: string;
  updated_at: string;
  id: string;
}

export type ObjectDetailDTOChildrenItem = {[key: string]: ObjectRelationDTO};

export type ObjectDetailDTOParentsItem = {[key: string]: ObjectRelationDTO};

export interface ObjectDetailDTO {
  id: string;
  object_type: string;
  state: string;
  fields: ObjectFieldDTO[];
  actions: ActionDTO[];
  created_at: string;
  updated_at: string;
  children?: ObjectDetailDTOChildrenItem[];
  parents?: ObjectDetailDTOParentsItem[];
}

export type ObjectFieldDTOLabel = string | null;

export interface ObjectFieldDTO {
  key: string;
  value: unknown;
  type: FieldType;
  label?: ObjectFieldDTOLabel;
  editable?: boolean;
}

export type ObjectListDTOSubtitle = string | null;

export type ObjectListDTOLink = string | null;

export interface ObjectListDTO {
  id: string;
  object_type: string;
  title: string;
  state: string;
  created_at: string;
  updated_at: string;
  subtitle?: ObjectListDTOSubtitle;
  actions?: ActionDTO[];
  fields?: ObjectFieldDTO[];
  link?: ObjectListDTOLink;
}

export type ObjectListRequestFiltersItem = TextFilterDefinition | RangeFilterDefinition | DateFilterDefinition | BooleanFilterDefinition;

export interface ObjectListRequest {
  limit?: number;
  offset?: number;
  filters?: ObjectListRequestFiltersItem[];
  sorts?: SortDefinition[];
}

export interface ObjectListResponse {
  objects: ObjectListDTO[];
  total: number;
  limit: number;
  offset: number;
  columns: ColumnDefinitionDTO[];
  actions?: ActionDTO[];
}

export interface ObjectRelationDTO {
  object_type: string;
  sqid: string;
  title: string;
}

export type ObjectTypes = typeof ObjectTypes[keyof typeof ObjectTypes];


 
export const ObjectTypes = {
  users: 'users',
  brands: 'brands',
  brandcontacts: 'brandcontacts',
  campaigns: 'campaigns',
  posts: 'posts',
  media: 'media',
  invoices: 'invoices',
} as const;

export type RangeFilterDefinitionStart = number | number | null;

export type RangeFilterDefinitionFinish = number | number | null;

export interface RangeFilterDefinition {
  column: string;
  start?: RangeFilterDefinitionStart;
  finish?: RangeFilterDefinitionFinish;
  type: 'range_filter';
}

export type SocialMediaPlatforms = typeof SocialMediaPlatforms[keyof typeof SocialMediaPlatforms];


 
export const SocialMediaPlatforms = {
  instagram: 'instagram',
  facebook: 'facebook',
  tiktok: 'tiktok',
  youtube: 'youtube',
} as const;

export interface SortDefinition {
  column: string;
  direction: SortDirection;
}

/**
 * Sort direction options.
 */
export type SortDirection = typeof SortDirection[keyof typeof SortDirection];


 
export const SortDirection = {
  sort_asc: 'sort_asc',
  sort_desc: 'sort_desc',
} as const;

export type TextFilterDefinitionOperation = typeof TextFilterDefinitionOperation[keyof typeof TextFilterDefinitionOperation];


 
export const TextFilterDefinitionOperation = {
  contains: 'contains',
  starts_with: 'starts_with',
  ends_with: 'ends_with',
  equals: 'equals',
} as const;

export interface TextFilterDefinition {
  column: string;
  operation: TextFilterDefinitionOperation;
  value: string;
  type: 'text_filter';
}

export type UpdateBrandBrandResponseBodyDescription = string | null;

export type UpdateBrandBrandResponseBodyToneOfVoice = string | null;

export type UpdateBrandBrandResponseBodyBrandValues = string | null;

export type UpdateBrandBrandResponseBodyTargetAudience = string | null;

export type UpdateBrandBrandResponseBodyWebsite = string | null;

export type UpdateBrandBrandResponseBodyEmail = string | null;

export type UpdateBrandBrandResponseBodyPhone = string | null;

export type UpdateBrandBrandResponseBodyNotes = string | null;

export interface UpdateBrandBrandResponseBody {
  name: string;
  description?: UpdateBrandBrandResponseBodyDescription;
  tone_of_voice?: UpdateBrandBrandResponseBodyToneOfVoice;
  brand_values?: UpdateBrandBrandResponseBodyBrandValues;
  target_audience?: UpdateBrandBrandResponseBodyTargetAudience;
  website?: UpdateBrandBrandResponseBodyWebsite;
  email?: UpdateBrandBrandResponseBodyEmail;
  phone?: UpdateBrandBrandResponseBodyPhone;
  notes?: UpdateBrandBrandResponseBodyNotes;
  created_at: string;
  updated_at: string;
  id: string;
}

export type UpdateBrandContactBrandContactResponseBodyEmail = string | null;

export type UpdateBrandContactBrandContactResponseBodyPhone = string | null;

export type UpdateBrandContactBrandContactResponseBodyNotes = string | null;

export interface UpdateBrandContactBrandContactResponseBody {
  first_name: string;
  last_name: string;
  email?: UpdateBrandContactBrandContactResponseBodyEmail;
  phone?: UpdateBrandContactBrandContactResponseBodyPhone;
  notes?: UpdateBrandContactBrandContactResponseBodyNotes;
  brand_id: number;
  created_at: string;
  updated_at: string;
  id: string;
}

export type UpdateCampaignCampaignResponseBodyDescription = string | null;

export interface UpdateCampaignCampaignResponseBody {
  name: string;
  description?: UpdateCampaignCampaignResponseBodyDescription;
  brand_id: number;
  created_at: string;
  updated_at: string;
  id: string;
}

export type UpdateInvoiceInvoiceResponseBodyDescription = string | null;

export type UpdateInvoiceInvoiceResponseBodyNotes = string | null;

export type UpdateInvoiceInvoiceResponseBodyCampaignId = number | null;

export interface UpdateInvoiceInvoiceResponseBody {
  invoice_number: number;
  customer_name: string;
  customer_email: string;
  posting_date: string;
  due_date: string;
  amount_due: number;
  amount_paid?: number;
  description?: UpdateInvoiceInvoiceResponseBodyDescription;
  notes?: UpdateInvoiceInvoiceResponseBodyNotes;
  campaign_id?: UpdateInvoiceInvoiceResponseBodyCampaignId;
  created_at: string;
  updated_at: string;
  id: string;
}

export interface UpdateMediaMediaResponseBody {
  filename: string;
  image_link: string;
  thumnbnail_link?: string;
  created_at: string;
  updated_at: string;
  id: string;
}

export type UpdateMediaSchemaFilename = string | null;

export type UpdateMediaSchemaImageLink = string | null;

export type UpdateMediaSchemaThumnbnailLink = string | null;

export interface UpdateMediaSchema {
  filename?: UpdateMediaSchemaFilename;
  image_link?: UpdateMediaSchemaImageLink;
  thumnbnail_link?: UpdateMediaSchemaThumnbnailLink;
}

export type UpdatePostPostResponseBodyContent = string | null;

export type UpdatePostPostResponseBodyNotes = {[key: string]: unknown};

export type UpdatePostPostResponseBodyCampaignId = number | null;

export interface UpdatePostPostResponseBody {
  title: string;
  content?: UpdatePostPostResponseBodyContent;
  platforms: SocialMediaPlatforms;
  posting_date: string;
  notes: UpdatePostPostResponseBodyNotes;
  compensation_structure?: CompensationStructure;
  campaign_id?: UpdatePostPostResponseBodyCampaignId;
  created_at: string;
  updated_at: string;
  id: string;
}

export type UserWaitlistFormSchemaCompany = string | null;

export type UserWaitlistFormSchemaMessage = string | null;

export interface UserWaitlistFormSchema {
  name: string;
  email: string;
  company?: UserWaitlistFormSchemaCompany;
  message?: UserWaitlistFormSchemaMessage;
}

export type HealthHealthCheck200 = { [key: string]: unknown };

export type UsersSignupAddUserToWaitlist400ExtraAnyOf = {[key: string]: unknown};

export type UsersSignupAddUserToWaitlist400Extra = null | UsersSignupAddUserToWaitlist400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type UsersSignupAddUserToWaitlist400 = {
  status_code: number;
  detail: string;
  extra?: UsersSignupAddUserToWaitlist400Extra;
};

export type UsersCreateUser400ExtraAnyOf = {[key: string]: unknown};

export type UsersCreateUser400Extra = null | UsersCreateUser400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type UsersCreateUser400 = {
  status_code: number;
  detail: string;
  extra?: UsersCreateUser400Extra;
};

export type UsersUserIdGetUser400ExtraAnyOf = {[key: string]: unknown};

export type UsersUserIdGetUser400Extra = null | UsersUserIdGetUser400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type UsersUserIdGetUser400 = {
  status_code: number;
  detail: string;
  extra?: UsersUserIdGetUser400Extra;
};

export type AuthGoogleLoginGoogleLogin200 = { [key: string]: unknown };

export type AuthGoogleCallbackGoogleCallbackParams = {
code?: string | null;
state?: string | null;
error?: string | null;
};

export type AuthGoogleCallbackGoogleCallback200 = { [key: string]: unknown };

export type AuthGoogleCallbackGoogleCallback400ExtraAnyOf = {[key: string]: unknown};

export type AuthGoogleCallbackGoogleCallback400Extra = null | AuthGoogleCallbackGoogleCallback400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type AuthGoogleCallbackGoogleCallback400 = {
  status_code: number;
  detail: string;
  extra?: AuthGoogleCallbackGoogleCallback400Extra;
};

export type OObjectTypeIdGetObjectDetail400ExtraAnyOf = {[key: string]: unknown};

export type OObjectTypeIdGetObjectDetail400Extra = null | OObjectTypeIdGetObjectDetail400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type OObjectTypeIdGetObjectDetail400 = {
  status_code: number;
  detail: string;
  extra?: OObjectTypeIdGetObjectDetail400Extra;
};

export type ListObjects400ExtraAnyOf = {[key: string]: unknown};

export type ListObjects400Extra = null | ListObjects400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type ListObjects400 = {
  status_code: number;
  detail: string;
  extra?: ListObjects400Extra;
};

export type BrandsIdGetBrand400ExtraAnyOf = {[key: string]: unknown};

export type BrandsIdGetBrand400Extra = null | BrandsIdGetBrand400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type BrandsIdGetBrand400 = {
  status_code: number;
  detail: string;
  extra?: BrandsIdGetBrand400Extra;
};

export type BrandsIdUpdateBrand400ExtraAnyOf = {[key: string]: unknown};

export type BrandsIdUpdateBrand400Extra = null | BrandsIdUpdateBrand400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type BrandsIdUpdateBrand400 = {
  status_code: number;
  detail: string;
  extra?: BrandsIdUpdateBrand400Extra;
};

export type BrandsContactsIdGetBrandContact400ExtraAnyOf = {[key: string]: unknown};

export type BrandsContactsIdGetBrandContact400Extra = null | BrandsContactsIdGetBrandContact400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type BrandsContactsIdGetBrandContact400 = {
  status_code: number;
  detail: string;
  extra?: BrandsContactsIdGetBrandContact400Extra;
};

export type BrandsContactsIdUpdateBrandContact400ExtraAnyOf = {[key: string]: unknown};

export type BrandsContactsIdUpdateBrandContact400Extra = null | BrandsContactsIdUpdateBrandContact400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type BrandsContactsIdUpdateBrandContact400 = {
  status_code: number;
  detail: string;
  extra?: BrandsContactsIdUpdateBrandContact400Extra;
};

export type CampaignsIdGetCampaign400ExtraAnyOf = {[key: string]: unknown};

export type CampaignsIdGetCampaign400Extra = null | CampaignsIdGetCampaign400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type CampaignsIdGetCampaign400 = {
  status_code: number;
  detail: string;
  extra?: CampaignsIdGetCampaign400Extra;
};

export type CampaignsIdUpdateCampaign400ExtraAnyOf = {[key: string]: unknown};

export type CampaignsIdUpdateCampaign400Extra = null | CampaignsIdUpdateCampaign400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type CampaignsIdUpdateCampaign400 = {
  status_code: number;
  detail: string;
  extra?: CampaignsIdUpdateCampaign400Extra;
};

export type PostsIdGetPost400ExtraAnyOf = {[key: string]: unknown};

export type PostsIdGetPost400Extra = null | PostsIdGetPost400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type PostsIdGetPost400 = {
  status_code: number;
  detail: string;
  extra?: PostsIdGetPost400Extra;
};

export type PostsIdUpdatePost400ExtraAnyOf = {[key: string]: unknown};

export type PostsIdUpdatePost400Extra = null | PostsIdUpdatePost400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type PostsIdUpdatePost400 = {
  status_code: number;
  detail: string;
  extra?: PostsIdUpdatePost400Extra;
};

export type MediaIdGetMedia400ExtraAnyOf = {[key: string]: unknown};

export type MediaIdGetMedia400Extra = null | MediaIdGetMedia400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type MediaIdGetMedia400 = {
  status_code: number;
  detail: string;
  extra?: MediaIdGetMedia400Extra;
};

export type MediaIdUpdateMedia400ExtraAnyOf = {[key: string]: unknown};

export type MediaIdUpdateMedia400Extra = null | MediaIdUpdateMedia400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type MediaIdUpdateMedia400 = {
  status_code: number;
  detail: string;
  extra?: MediaIdUpdateMedia400Extra;
};

export type InvoicesIdGetInvoice400ExtraAnyOf = {[key: string]: unknown};

export type InvoicesIdGetInvoice400Extra = null | InvoicesIdGetInvoice400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type InvoicesIdGetInvoice400 = {
  status_code: number;
  detail: string;
  extra?: InvoicesIdGetInvoice400Extra;
};

export type InvoicesIdUpdateInvoice400ExtraAnyOf = {[key: string]: unknown};

export type InvoicesIdUpdateInvoice400Extra = null | InvoicesIdUpdateInvoice400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type InvoicesIdUpdateInvoice400 = {
  status_code: number;
  detail: string;
  extra?: InvoicesIdUpdateInvoice400Extra;
};

