/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
export type AddUserToWaitlistWaitlistEntryResponseBodyCompany = string | null;

export type AddUserToWaitlistWaitlistEntryResponseBodyMessage = string | null;

export interface AddUserToWaitlistWaitlistEntryResponseBody {
  name: string;
  email: string;
  company?: AddUserToWaitlistWaitlistEntryResponseBodyCompany;
  message?: AddUserToWaitlistWaitlistEntryResponseBodyMessage;
  id: number;
  created_at: string;
  updated_at: string;
}

export interface CreateUserSchema {
  name: string;
  email: string;
}

export interface CreateUserUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  id: number;
  created_at: string;
  updated_at: string;
}

export interface CurrentUserResponse {
  id: number;
  name: string;
  email: string;
  email_verified: boolean;
}

export interface GetCurrentUserUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  id: number;
  created_at: string;
  updated_at: string;
}

export interface GetUserUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  id: number;
  created_at: string;
  updated_at: string;
}

export type GoogleUserInfoResponseSchemaPicture = string | null;

export interface GoogleUserInfoResponseSchema {
  google_id: string;
  email: string;
  name: string;
  picture?: GoogleUserInfoResponseSchemaPicture;
  user_id: number;
}

export interface ListUsersUserResponseBody {
  name: string;
  email: string;
  email_verified?: boolean;
  id: number;
  created_at: string;
  updated_at: string;
}

export type UserWaitlistFormSchemaCompany = string | null;

export type UserWaitlistFormSchemaMessage = string | null;

export interface UserWaitlistFormSchema {
  name: string;
  email: string;
  company?: UserWaitlistFormSchemaCompany;
  message?: UserWaitlistFormSchemaMessage;
}

export type HealthHealthCheck200 = { [key: string]: unknown };

export type UsersCreateUser400ExtraAnyOf = { [key: string]: unknown };

export type UsersCreateUser400Extra =
  | null
  | UsersCreateUser400ExtraAnyOf
  | unknown[];

/**
 * Validation Exception
 */
export type UsersCreateUser400 = {
  status_code: number;
  detail: string;
  extra?: UsersCreateUser400Extra;
};

export type UsersUserIdGetUser400ExtraAnyOf = { [key: string]: unknown };

export type UsersUserIdGetUser400Extra =
  | null
  | UsersUserIdGetUser400ExtraAnyOf
  | unknown[];

/**
 * Validation Exception
 */
export type UsersUserIdGetUser400 = {
  status_code: number;
  detail: string;
  extra?: UsersUserIdGetUser400Extra;
};

export type UsersSignupAddUserToWaitlist400ExtraAnyOf = {
  [key: string]: unknown;
};

export type UsersSignupAddUserToWaitlist400Extra =
  | null
  | UsersSignupAddUserToWaitlist400ExtraAnyOf
  | unknown[];

/**
 * Validation Exception
 */
export type UsersSignupAddUserToWaitlist400 = {
  status_code: number;
  detail: string;
  extra?: UsersSignupAddUserToWaitlist400Extra;
};

export type AuthLogoutLogoutUserParams = {
  connection: unknown;
};

export type AuthLogoutLogoutUser201 = { [key: string]: string };

export type AuthLogoutLogoutUser400ExtraAnyOf = { [key: string]: unknown };

export type AuthLogoutLogoutUser400Extra =
  | null
  | AuthLogoutLogoutUser400ExtraAnyOf
  | unknown[];

/**
 * Validation Exception
 */
export type AuthLogoutLogoutUser400 = {
  status_code: number;
  detail: string;
  extra?: AuthLogoutLogoutUser400Extra;
};

export type AuthProfileGetUserProfileParams = {
  connection: unknown;
};

export type AuthProfileGetUserProfile400ExtraAnyOf = { [key: string]: unknown };

export type AuthProfileGetUserProfile400Extra =
  | null
  | AuthProfileGetUserProfile400ExtraAnyOf
  | unknown[];

/**
 * Validation Exception
 */
export type AuthProfileGetUserProfile400 = {
  status_code: number;
  detail: string;
  extra?: AuthProfileGetUserProfile400Extra;
};

export type AuthAdminUsersUserIdDeleteUser200 = { [key: string]: string };

export type AuthAdminUsersUserIdDeleteUser400ExtraAnyOf = {
  [key: string]: unknown;
};

export type AuthAdminUsersUserIdDeleteUser400Extra =
  | null
  | AuthAdminUsersUserIdDeleteUser400ExtraAnyOf
  | unknown[];

/**
 * Validation Exception
 */
export type AuthAdminUsersUserIdDeleteUser400 = {
  status_code: number;
  detail: string;
  extra?: AuthAdminUsersUserIdDeleteUser400Extra;
};

export type AuthGoogleLoginGoogleLogin200 = { [key: string]: unknown };

export type AuthGoogleCallbackGoogleCallbackParams = {
  code?: string | null;
  state?: string | null;
  error?: string | null;
};

export type AuthGoogleCallbackGoogleCallback200 = { [key: string]: unknown };

export type AuthGoogleCallbackGoogleCallback400ExtraAnyOf = {
  [key: string]: unknown;
};

export type AuthGoogleCallbackGoogleCallback400Extra =
  | null
  | AuthGoogleCallbackGoogleCallback400ExtraAnyOf
  | unknown[];

/**
 * Validation Exception
 */
export type AuthGoogleCallbackGoogleCallback400 = {
  status_code: number;
  detail: string;
  extra?: AuthGoogleCallbackGoogleCallback400Extra;
};

/**
 * @summary HealthCheck
 */
export type healthHealthCheckResponse200 = {
  data: HealthHealthCheck200;
  status: 200;
};

export type healthHealthCheckResponseComposite = healthHealthCheckResponse200;

export type healthHealthCheckResponse = healthHealthCheckResponseComposite & {
  headers: Headers;
};

export const getHealthHealthCheckUrl = () => {
  return `/health`;
};

export const healthHealthCheck = async (
  options?: RequestInit
): Promise<healthHealthCheckResponse> => {
  const res = await fetch(getHealthHealthCheckUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: healthHealthCheckResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthHealthCheckResponse;
};

/**
 * @summary ListUsers
 */
export type usersListUsersResponse200 = {
  data: ListUsersUserResponseBody[];
  status: 200;
};

export type usersListUsersResponseComposite = usersListUsersResponse200;

export type usersListUsersResponse = usersListUsersResponseComposite & {
  headers: Headers;
};

export const getUsersListUsersUrl = () => {
  return `/users`;
};

export const usersListUsers = async (
  options?: RequestInit
): Promise<usersListUsersResponse> => {
  const res = await fetch(getUsersListUsersUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: usersListUsersResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as usersListUsersResponse;
};

/**
 * @summary CreateUser
 */
export type usersCreateUserResponse201 = {
  data: CreateUserUserResponseBody;
  status: 201;
};

export type usersCreateUserResponse400 = {
  data: UsersCreateUser400;
  status: 400;
};

export type usersCreateUserResponseComposite =
  | usersCreateUserResponse201
  | usersCreateUserResponse400;

export type usersCreateUserResponse = usersCreateUserResponseComposite & {
  headers: Headers;
};

export const getUsersCreateUserUrl = () => {
  return `/users`;
};

export const usersCreateUser = async (
  createUserSchema: CreateUserSchema,
  options?: RequestInit
): Promise<usersCreateUserResponse> => {
  const res = await fetch(getUsersCreateUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUserSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: usersCreateUserResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as usersCreateUserResponse;
};

/**
 * @summary GetUser
 */
export type usersUserIdGetUserResponse200 = {
  data: GetUserUserResponseBody;
  status: 200;
};

export type usersUserIdGetUserResponse400 = {
  data: UsersUserIdGetUser400;
  status: 400;
};

export type usersUserIdGetUserResponseComposite =
  | usersUserIdGetUserResponse200
  | usersUserIdGetUserResponse400;

export type usersUserIdGetUserResponse = usersUserIdGetUserResponseComposite & {
  headers: Headers;
};

export const getUsersUserIdGetUserUrl = (userId: number) => {
  return `/users/${userId}`;
};

export const usersUserIdGetUser = async (
  userId: number,
  options?: RequestInit
): Promise<usersUserIdGetUserResponse> => {
  const res = await fetch(getUsersUserIdGetUserUrl(userId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: usersUserIdGetUserResponse['data'] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as usersUserIdGetUserResponse;
};

/**
 * @summary AddUserToWaitlist
 */
export type usersSignupAddUserToWaitlistResponse201 = {
  data: AddUserToWaitlistWaitlistEntryResponseBody;
  status: 201;
};

export type usersSignupAddUserToWaitlistResponse400 = {
  data: UsersSignupAddUserToWaitlist400;
  status: 400;
};

export type usersSignupAddUserToWaitlistResponseComposite =
  | usersSignupAddUserToWaitlistResponse201
  | usersSignupAddUserToWaitlistResponse400;

export type usersSignupAddUserToWaitlistResponse =
  usersSignupAddUserToWaitlistResponseComposite & {
    headers: Headers;
  };

export const getUsersSignupAddUserToWaitlistUrl = () => {
  return `/users/signup`;
};

export const usersSignupAddUserToWaitlist = async (
  userWaitlistFormSchema: UserWaitlistFormSchema,
  options?: RequestInit
): Promise<usersSignupAddUserToWaitlistResponse> => {
  const res = await fetch(getUsersSignupAddUserToWaitlistUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userWaitlistFormSchema),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: usersSignupAddUserToWaitlistResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as usersSignupAddUserToWaitlistResponse;
};

/**
 * @summary GetCurrentUser
 */
export type usersCurrentUserGetCurrentUserResponse200 = {
  data: GetCurrentUserUserResponseBody;
  status: 200;
};

export type usersCurrentUserGetCurrentUserResponseComposite =
  usersCurrentUserGetCurrentUserResponse200;

export type usersCurrentUserGetCurrentUserResponse =
  usersCurrentUserGetCurrentUserResponseComposite & {
    headers: Headers;
  };

export const getUsersCurrentUserGetCurrentUserUrl = () => {
  return `/users/current_user`;
};

export const usersCurrentUserGetCurrentUser = async (
  options?: RequestInit
): Promise<usersCurrentUserGetCurrentUserResponse> => {
  const res = await fetch(getUsersCurrentUserGetCurrentUserUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: usersCurrentUserGetCurrentUserResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as usersCurrentUserGetCurrentUserResponse;
};

/**
 * @summary LogoutUser
 */
export type authLogoutLogoutUserResponse201 = {
  data: AuthLogoutLogoutUser201;
  status: 201;
};

export type authLogoutLogoutUserResponse400 = {
  data: AuthLogoutLogoutUser400;
  status: 400;
};

export type authLogoutLogoutUserResponseComposite =
  | authLogoutLogoutUserResponse201
  | authLogoutLogoutUserResponse400;

export type authLogoutLogoutUserResponse =
  authLogoutLogoutUserResponseComposite & {
    headers: Headers;
  };

export const getAuthLogoutLogoutUserUrl = (
  params: AuthLogoutLogoutUserParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/logout?${stringifiedParams}`
    : `/auth/logout`;
};

export const authLogoutLogoutUser = async (
  params: AuthLogoutLogoutUserParams,
  options?: RequestInit
): Promise<authLogoutLogoutUserResponse> => {
  const res = await fetch(getAuthLogoutLogoutUserUrl(params), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: authLogoutLogoutUserResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authLogoutLogoutUserResponse;
};

/**
 * @summary GetUserProfile
 */
export type authProfileGetUserProfileResponse200 = {
  data: CurrentUserResponse;
  status: 200;
};

export type authProfileGetUserProfileResponse400 = {
  data: AuthProfileGetUserProfile400;
  status: 400;
};

export type authProfileGetUserProfileResponseComposite =
  | authProfileGetUserProfileResponse200
  | authProfileGetUserProfileResponse400;

export type authProfileGetUserProfileResponse =
  authProfileGetUserProfileResponseComposite & {
    headers: Headers;
  };

export const getAuthProfileGetUserProfileUrl = (
  params: AuthProfileGetUserProfileParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/profile?${stringifiedParams}`
    : `/auth/profile`;
};

export const authProfileGetUserProfile = async (
  params: AuthProfileGetUserProfileParams,
  options?: RequestInit
): Promise<authProfileGetUserProfileResponse> => {
  const res = await fetch(getAuthProfileGetUserProfileUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: authProfileGetUserProfileResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authProfileGetUserProfileResponse;
};

/**
 * @summary ListAllUsers
 */
export type authAdminUsersListAllUsersResponse200 = {
  data: CurrentUserResponse[];
  status: 200;
};

export type authAdminUsersListAllUsersResponseComposite =
  authAdminUsersListAllUsersResponse200;

export type authAdminUsersListAllUsersResponse =
  authAdminUsersListAllUsersResponseComposite & {
    headers: Headers;
  };

export const getAuthAdminUsersListAllUsersUrl = () => {
  return `/auth/admin/users`;
};

export const authAdminUsersListAllUsers = async (
  options?: RequestInit
): Promise<authAdminUsersListAllUsersResponse> => {
  const res = await fetch(getAuthAdminUsersListAllUsersUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: authAdminUsersListAllUsersResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authAdminUsersListAllUsersResponse;
};

/**
 * @summary DeleteUser
 */
export type authAdminUsersUserIdDeleteUserResponse200 = {
  data: AuthAdminUsersUserIdDeleteUser200;
  status: 200;
};

export type authAdminUsersUserIdDeleteUserResponse400 = {
  data: AuthAdminUsersUserIdDeleteUser400;
  status: 400;
};

export type authAdminUsersUserIdDeleteUserResponseComposite =
  | authAdminUsersUserIdDeleteUserResponse200
  | authAdminUsersUserIdDeleteUserResponse400;

export type authAdminUsersUserIdDeleteUserResponse =
  authAdminUsersUserIdDeleteUserResponseComposite & {
    headers: Headers;
  };

export const getAuthAdminUsersUserIdDeleteUserUrl = (userId: number) => {
  return `/auth/admin/users/${userId}`;
};

export const authAdminUsersUserIdDeleteUser = async (
  userId: number,
  options?: RequestInit
): Promise<authAdminUsersUserIdDeleteUserResponse> => {
  const res = await fetch(getAuthAdminUsersUserIdDeleteUserUrl(userId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: authAdminUsersUserIdDeleteUserResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authAdminUsersUserIdDeleteUserResponse;
};

/**
 * @summary GoogleLogin
 */
export type authGoogleLoginGoogleLoginResponse200 = {
  data: AuthGoogleLoginGoogleLogin200;
  status: 200;
};

export type authGoogleLoginGoogleLoginResponseComposite =
  authGoogleLoginGoogleLoginResponse200;

export type authGoogleLoginGoogleLoginResponse =
  authGoogleLoginGoogleLoginResponseComposite & {
    headers: Headers;
  };

export const getAuthGoogleLoginGoogleLoginUrl = () => {
  return `/auth/google/login`;
};

export const authGoogleLoginGoogleLogin = async (
  options?: RequestInit
): Promise<authGoogleLoginGoogleLoginResponse> => {
  const res = await fetch(getAuthGoogleLoginGoogleLoginUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: authGoogleLoginGoogleLoginResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authGoogleLoginGoogleLoginResponse;
};

/**
 * @summary GoogleCallback
 */
export type authGoogleCallbackGoogleCallbackResponse200 = {
  data: AuthGoogleCallbackGoogleCallback200;
  status: 200;
};

export type authGoogleCallbackGoogleCallbackResponse400 = {
  data: AuthGoogleCallbackGoogleCallback400;
  status: 400;
};

export type authGoogleCallbackGoogleCallbackResponseComposite =
  | authGoogleCallbackGoogleCallbackResponse200
  | authGoogleCallbackGoogleCallbackResponse400;

export type authGoogleCallbackGoogleCallbackResponse =
  authGoogleCallbackGoogleCallbackResponseComposite & {
    headers: Headers;
  };

export const getAuthGoogleCallbackGoogleCallbackUrl = (
  params?: AuthGoogleCallbackGoogleCallbackParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/auth/google/callback?${stringifiedParams}`
    : `/auth/google/callback`;
};

export const authGoogleCallbackGoogleCallback = async (
  params?: AuthGoogleCallbackGoogleCallbackParams,
  options?: RequestInit
): Promise<authGoogleCallbackGoogleCallbackResponse> => {
  const res = await fetch(getAuthGoogleCallbackGoogleCallbackUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: authGoogleCallbackGoogleCallbackResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authGoogleCallbackGoogleCallbackResponse;
};

/**
 * @summary GetCurrentUserGoogleInfo
 */
export type authGoogleMeGetCurrentUserGoogleInfoResponse200 = {
  data: GoogleUserInfoResponseSchema;
  status: 200;
};

export type authGoogleMeGetCurrentUserGoogleInfoResponseComposite =
  authGoogleMeGetCurrentUserGoogleInfoResponse200;

export type authGoogleMeGetCurrentUserGoogleInfoResponse =
  authGoogleMeGetCurrentUserGoogleInfoResponseComposite & {
    headers: Headers;
  };

export const getAuthGoogleMeGetCurrentUserGoogleInfoUrl = () => {
  return `/auth/google/me`;
};

export const authGoogleMeGetCurrentUserGoogleInfo = async (
  options?: RequestInit
): Promise<authGoogleMeGetCurrentUserGoogleInfoResponse> => {
  const res = await fetch(getAuthGoogleMeGetCurrentUserGoogleInfoUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: authGoogleMeGetCurrentUserGoogleInfoResponse['data'] = body
    ? JSON.parse(body)
    : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as authGoogleMeGetCurrentUserGoogleInfoResponse;
};
