/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ManagerLab
 * Private schema of ManagerLab with Scalar OpenAPI docs
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  OObjectTypeIdGetObjectDetail400,
  OObjectTypeListObjects400,
  ObjectDetailDTO,
  ObjectListRequest,
  ObjectListResponse,
  ObjectTypes
} from '../managerLab.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary GetObjectDetail
 */
export const oObjectTypeIdGetObjectDetail = (
    objectType: ObjectTypes,
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ObjectDetailDTO>(
      {url: `/o/${objectType}/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getOObjectTypeIdGetObjectDetailQueryKey = (objectType?: ObjectTypes,
    id?: string,) => {
    return [`/o/${objectType}/${id}`] as const;
    }

    
export const getOObjectTypeIdGetObjectDetailQueryOptions = <TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(objectType: ObjectTypes,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOObjectTypeIdGetObjectDetailQueryKey(objectType,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>> = ({ signal }) => oObjectTypeIdGetObjectDetail(objectType,id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(objectType && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OObjectTypeIdGetObjectDetailQueryResult = NonNullable<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>>
export type OObjectTypeIdGetObjectDetailQueryError = OObjectTypeIdGetObjectDetail400


export function useOObjectTypeIdGetObjectDetail<TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(
 objectType: ObjectTypes,
    id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>,
          TError,
          Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOObjectTypeIdGetObjectDetail<TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(
 objectType: ObjectTypes,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>,
          TError,
          Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOObjectTypeIdGetObjectDetail<TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(
 objectType: ObjectTypes,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetObjectDetail
 */

export function useOObjectTypeIdGetObjectDetail<TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(
 objectType: ObjectTypes,
    id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOObjectTypeIdGetObjectDetailQueryOptions(objectType,id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getOObjectTypeIdGetObjectDetailSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(objectType: ObjectTypes,
    id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOObjectTypeIdGetObjectDetailQueryKey(objectType,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>> = ({ signal }) => oObjectTypeIdGetObjectDetail(objectType,id, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OObjectTypeIdGetObjectDetailSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>>
export type OObjectTypeIdGetObjectDetailSuspenseQueryError = OObjectTypeIdGetObjectDetail400


export function useOObjectTypeIdGetObjectDetailSuspense<TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(
 objectType: ObjectTypes,
    id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOObjectTypeIdGetObjectDetailSuspense<TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(
 objectType: ObjectTypes,
    id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOObjectTypeIdGetObjectDetailSuspense<TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(
 objectType: ObjectTypes,
    id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetObjectDetail
 */

export function useOObjectTypeIdGetObjectDetailSuspense<TData = Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError = OObjectTypeIdGetObjectDetail400>(
 objectType: ObjectTypes,
    id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof oObjectTypeIdGetObjectDetail>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOObjectTypeIdGetObjectDetailSuspenseQueryOptions(objectType,id,options)

  const query = useSuspenseQuery(queryOptions , queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary ListObjects
 */
export const oObjectTypeListObjects = (
    objectType: ObjectTypes,
    objectListRequest: ObjectListRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<ObjectListResponse>(
      {url: `/o/${objectType}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: objectListRequest, signal
    },
      );
    }
  


export const getOObjectTypeListObjectsMutationOptions = <TError = OObjectTypeListObjects400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof oObjectTypeListObjects>>, TError,{objectType: ObjectTypes;data: ObjectListRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof oObjectTypeListObjects>>, TError,{objectType: ObjectTypes;data: ObjectListRequest}, TContext> => {

const mutationKey = ['oObjectTypeListObjects'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof oObjectTypeListObjects>>, {objectType: ObjectTypes;data: ObjectListRequest}> = (props) => {
          const {objectType,data} = props ?? {};

          return  oObjectTypeListObjects(objectType,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OObjectTypeListObjectsMutationResult = NonNullable<Awaited<ReturnType<typeof oObjectTypeListObjects>>>
    export type OObjectTypeListObjectsMutationBody = ObjectListRequest
    export type OObjectTypeListObjectsMutationError = OObjectTypeListObjects400

    /**
 * @summary ListObjects
 */
export const useOObjectTypeListObjects = <TError = OObjectTypeListObjects400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof oObjectTypeListObjects>>, TError,{objectType: ObjectTypes;data: ObjectListRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof oObjectTypeListObjects>>,
        TError,
        {objectType: ObjectTypes;data: ObjectListRequest},
        TContext
      > => {

      const mutationOptions = getOObjectTypeListObjectsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    